(()=>{ 'use strict';
const VERSION='0.9.0',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const load=(k,d)=>{try{const v=localStorage.getItem(k);return v==null?d:JSON.parse(v)}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let api,adminUnlocked=false,liveLocked=load('fosa_live_locked',false),mode=load('fosa_usage_mode','rehearsal'),lastJoined=false,lastCount=0,bgActive=false,quickTalkTarget=null;
const remoteStates=new Map(),defaults={roles:['Chef','Piano','Basse','Batterie','Guitare','Chant','Sono','Autre'],groups:[{name:'Rythmique',roles:['Piano','Basse','Batterie','Guitare']},{name:'Chant',roles:['Chant']},{name:'Sono',roles:['Sono']}]};
let customRoles=load('fosa_custom_roles',[]),customGroups=load('fosa_custom_groups',defaults.groups),favorites=load('fosa_favorites',[]),history=load('fosa_history',[]);
function log(msg){history.unshift({t:Date.now(),msg});history=history.slice(0,120);save('fosa_history',history);renderHistory()}
function toast(title,desc='',actions=[]){$('.v080-toast')?.remove();const el=document.createElement('div');el.className='v080-toast';el.innerHTML=`<b>${esc(title)}</b>${desc?`<div class="small">${esc(desc)}</div>`:''}<div class="v080-toast-actions"></div>`;const box=el.querySelector('.v080-toast-actions');actions.forEach(a=>{const b=document.createElement('button');b.textContent=a.label;b.className=a.primary?'primary':'';b.onclick=()=>{a.run?.();el.remove()};box.appendChild(b)});if(!actions.length)setTimeout(()=>el.remove(),2400);document.body.appendChild(el)}
const state=()=>api?.getState?.()||{};
function setMode(x){mode=x==='concert'?'concert':'rehearsal';save('fosa_usage_mode',mode);document.body.classList.toggle('fosa-concert',mode==='concert');$$('[data-usage-mode]').forEach(b=>b.classList.toggle('active',b.dataset.usageMode===mode));if(mode==='concert'&&!liveLocked)setLock(true)}
function setLock(v){liveLocked=!!v;save('fosa_live_locked',liveLocked);document.body.classList.toggle('fosa-live-locked',liveLocked);const b=$('#v080Lock');if(b){b.classList.toggle('active',liveLocked);b.textContent=liveLocked?'🔒':'🔓';b.title=liveLocked?'LIVE verrouillé':'Verrouiller LIVE'}}
function syncRoleOptions(){const sel=$('#role');if(!sel)return;const current=sel.value;customRoles.forEach(r=>{if(![...sel.options].some(o=>o.value===r)){const o=document.createElement('option');o.value=o.textContent=r;sel.appendChild(o)}});if([...sel.options].some(o=>o.value===current))sel.value=current;renderRoleChecks()}
function customTargetName(t){if(t==='all')return'TOUS';if(t.startsWith('role:'))return t.slice(5).toUpperCase();if(t.startsWith('custom:'))return t.slice(7).toUpperCase();if(t.startsWith('peer:')){const p=(api.getParticipants?.()||[]).find(x=>x.peerId===t.slice(5));return p?.name?.toUpperCase()||'PERSONNE'}return t.toUpperCase()}
function allQuickTargets(){const s=state(),out=[{target:'all',label:'TOUS'}];if(s.role==='Chef')out.push(...customGroups.map(g=>({target:'custom:'+g.name,label:g.name.toUpperCase()})));for(const f of favorites)if(!out.some(x=>x.target===f.target))out.push(f);return out.slice(0,10)}
function renderQuick(){const wrap=$('#v080QuickTargets');if(!wrap)return;wrap.innerHTML=allQuickTargets().map(x=>`<button class="v080-qptt" data-qtarget="${esc(x.target)}">${esc(x.label||customTargetName(x.target))}</button>`).join('')}
function pressTarget(btn){if(liveLocked&&mode==='concert'&&btn.dataset.qtarget==='all'&&state().role!=='Chef'){toast('LIVE verrouillé','Destination générale réservée au Chef en mode Concert.');return}quickTalkTarget=btn.dataset.qtarget;api.setTarget(quickTalkTarget);btn.classList.add('talking');api.startTalk()}
function releaseTarget(){if(!quickTalkTarget)return;api.stopTalk();$$('[data-qtarget]').forEach(b=>b.classList.remove('talking'));quickTalkTarget=null}
function renderHistory(){const el=$('#v080History');if(!el)return;el.innerHTML=history.length?history.slice(0,40).map(h=>`<div>${new Date(h.t).toLocaleString()} · ${esc(h.msg)}</div>`).join(''):'<div>Aucun événement enregistré.</div>'}
function addFavoriteCurrent(){const s=state();if(!s.target)return;const f={target:s.target,label:customTargetName(s.target)};favorites=favorites.filter(x=>x.target!==f.target);favorites.unshift(f);favorites=favorites.slice(0,8);save('fosa_favorites',favorites);renderQuick();renderFavorites();toast('Favori ajouté',f.label)}
function renderFavorites(){const el=$('#v080Favorites');if(!el)return;el.innerHTML=favorites.length?favorites.map(f=>`<button class="v080-chip" data-remove-fav="${esc(f.target)}">★ ${esc(f.label)}</button>`).join(''):'<span class="small">Aucun favori.</span>'}
function renderRoleChecks(){const el=$('#v080RoleChecks');if(!el)return;const roles=[...new Set([...defaults.roles,...customRoles])];el.innerHTML=roles.map(r=>`<label class="v080-badge"><input type="checkbox" value="${esc(r)}"> ${esc(r)}</label>`).join(' ')}
function renderGroups(){const el=$('#v080Groups');if(!el)return;el.innerHTML=customGroups.length?customGroups.map((g,i)=>`<div class="menuLine"><span>${esc(g.name)}</span><b>${esc(g.roles.join(', '))} <button data-del-group="${i}" style="padding:4px 6px">×</button></b></div>`).join(''):'<span class="small">Aucun groupe.</span>';renderQuick()}
async function hashPin(v){const data=new TextEncoder().encode('fosa-v080:'+v),h=await crypto.subtle.digest('SHA-256',data);return[...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function setPin(){const v=$('#v080Pin').value.trim();if(v.length<4){toast('PIN trop court','Utilisez au moins 4 caractères.');return}localStorage.fosa_admin_pin_hash=await hashPin(v);adminUnlocked=true;$('#v080Pin').value='';updateAdmin();toast('PIN enregistré','Contrôles administrateur déverrouillés sur cet appareil.')}
async function unlockPin(){const expected=localStorage.fosa_admin_pin_hash;if(!expected){toast('Aucun PIN','Définissez d’abord le PIN administrateur.');return}const v=$('#v080Pin').value;adminUnlocked=(await hashPin(v))===expected;$('#v080Pin').value='';updateAdmin();toast(adminUnlocked?'Administration déverrouillée':'PIN incorrect')}
function updateAdmin(){const b=$('#v080AdminState');if(b){b.textContent=adminUnlocked?'ADMIN DÉVERROUILLÉ':'ADMIN VERROUILLÉ';b.className='v080-badge '+(adminUnlocked?'on':'warn')}decoratePeers()}
function sendRemote(to,action,value){if(!state().hosting||!adminUnlocked){toast('Contrôle protégé','Déverrouillez le mode administrateur sur l’hôte.');return}api.sendControl({kind:'remote',to,action,value,admin:true});log(`Commande ${action}=${value?'ON':'OFF'} → ${to.slice(0,6)}`)}
function decoratePeers(){const can=state().hosting&&adminUnlocked;$$('#people .person').forEach(card=>{card.classList.toggle('chef',card.querySelector('.role')?.textContent?.trim().startsWith('Chef'));const listen=card.querySelector('[data-listen]');if(!listen){card.querySelector('.v080-peer-tools')?.remove();return}const rid=listen.dataset.listen;let tools=card.querySelector('.v080-peer-tools');if(!can){tools?.remove();return}if(!tools){tools=document.createElement('div');tools.className='v080-peer-tools';card.appendChild(tools)}const rs=remoteStates.get(rid)||{mic:true,input:true,output:true};const signature=JSON.stringify(rs);if(tools.dataset.state===signature)return;tools.dataset.state=signature;tools.innerHTML=`<button data-remote="mic" data-rid="${rid}">MIC ${rs.mic?'ON':'OFF'}</button><button data-remote="input" data-rid="${rid}">IN ${rs.input?'ON':'OFF'}</button><button data-remote="output" data-rid="${rid}">OUT ${rs.output?'ON':'OFF'}</button>`})}
function callChef(){const s=state();api.sendControl({kind:'call-chef',fromName:s.name,fromRole:s.role});toast('Appel envoyé','Le Chef voit votre demande de communication.');log('Appel Chef envoyé')}
function handleControl(p){if(!p||p.from===api.peerId)return;const s=state();if(p.kind==='remote'&&(p.to===api.peerId||p.to==='all')){if(localStorage.fosa_allow_remote_control==='0')return;if(p.action==='mic')api.setMic(!!p.value);if(p.action==='input')api.setIn(!!p.value);if(p.action==='output')api.setOut(!!p.value);toast('Commande du Chef',`${p.action.toUpperCase()} ${p.value?'ON':'OFF'}`);log(`Commande distante: ${p.action} ${p.value?'ON':'OFF'}`)}if(p.kind==='call-chef'&&s.role==='Chef'){toast(`${p.fromName||'Un participant'} appelle le Chef`,p.fromRole||'',[{label:'PARLER',primary:true,run:()=>{api.setTarget('peer:'+p.from);$('#lock')?.click();api.startTalk()}},{label:'FERMER',run:()=>{}}]);log(`Appel reçu de ${p.fromName||p.from}`)}}
async function preflight(){const meter=$('#v080Meter i'),statusEl=$('#v080PreflightStatus');if(!navigator.mediaDevices?.getUserMedia){statusEl.textContent='Micro non disponible';return}statusEl.textContent='Test du micro…';try{const st=await navigator.mediaDevices.getUserMedia({audio:true});const ac=new AudioContext({latencyHint:'interactive'}),src=ac.createMediaStreamSource(st),an=ac.createAnalyser();an.fftSize=512;src.connect(an);const a=new Uint8Array(an.frequencyBinCount);let peak=0;await new Promise(resolve=>{const start=performance.now();const tick=()=>{an.getByteFrequencyData(a);const avg=a.reduce((x,y)=>x+y,0)/a.length;peak=Math.max(peak,avg);if(meter)meter.style.width=Math.min(100,avg*1.4)+'%';if(performance.now()-start<1800)requestAnimationFrame(tick);else resolve()};tick()});st.getTracks().forEach(t=>t.stop());await ac.close();const conn=navigator.connection,net=conn?`${conn.effectiveType||'réseau'}${conn.rtt?` · ${conn.rtt} ms`:''}`:'réseau disponible';statusEl.textContent=(peak>3?'PRÊT':'MICRO FAIBLE')+' · '+net;statusEl.className='small '+(peak>3?'v080-ok':'v080-warn');log('Test avant live: '+statusEl.textContent)}catch(e){statusEl.textContent='ATTENTION · '+e.name;statusEl.className='small v080-warn'}}
async function persistentNotification(on){bgActive=!!on;save('fosa_background_mode',bgActive);updateBackgroundUi();if(!on){try{const reg=await navigator.serviceWorker?.ready;for(const n of await reg?.getNotifications?.({tag:'fosa-live'})||[])n.close()}catch{}return}if('Notification'in window&&Notification.permission!=='granted'){try{await Notification.requestPermission()}catch{}}showLiveNotification()}
async function showLiveNotification(){if(!bgActive||!state().joined)return;try{const reg=await navigator.serviceWorker?.ready;await reg?.showNotification?.('FOSA · LIVE actif',{body:`${state().name||'FOSA'} · ${state().role||''} · ${state().room||''}`,tag:'fosa-live',renotify:false,requireInteraction:true,silent:true,icon:'./fosa-icon.svg',badge:'./fosa-icon.svg',data:{url:location.href}})}catch{}try{if('mediaSession'in navigator)navigator.mediaSession.metadata=new MediaMetadata({title:'FOSA LIVE',artist:`${state().role||''} · ${state().room||''}`,album:'Talkback actif'})}catch{}}
function updateBackgroundUi(){const b=$('#v080Bg');if(b){b.classList.toggle('active',bgActive);b.textContent=bgActive?'ARRIÈRE-PLAN ON':'ARRIÈRE-PLAN OFF'}const n=$('#v080BgNote');if(n)n.textContent=/Android/i.test(navigator.userAgent)?'La PWA maintient la session autant que le navigateur le permet. Pour une persistance garantie, utilisez l’application Android native avec service au premier plan.':'Sur PC, la notification reste visible et FOSA tente de maintenir la session active quand vous changez d’application.'}
function qr(){const box=$('#v080Qr');if(!box)return;box.innerHTML='';const s=state(),value=`${location.origin}${location.pathname}?room=${encodeURIComponent(s.room||$('#room')?.value||'')}`;if(window.QRCode)new QRCode(box,{text:value,width:180,height:180,colorDark:'#000000',colorLight:'#ffffff'});else box.textContent=value}
function restoreQuery(){const q=new URLSearchParams(location.search),room=q.get('room');if(room&&$('#room'))$('#room').value=room.toUpperCase().slice(0,8)}
function autoRejoin(){if(localStorage.fosa_auto_rejoin!=='1')return;const x=load('fosa_last_session',null);if(!x?.room)return;const n=$('#name'),r=$('#role'),room=$('#room');if(n&&!n.value)n.value=x.name||'';if(r&&x.role){syncRoleOptions();r.value=x.role}if(room)room.value=x.room;setTimeout(()=>{if(!state().joined&&$('#join')&&!$('#join').classList.contains('hidden')){$('#join').click();toast('Reconnexion automatique','Tentative de retour dans la dernière session.')}},850)}
function updateJoinState(){const s=state();if(s.joined!==lastJoined){lastJoined=s.joined;if(s.joined){save('fosa_last_session',{room:s.room,name:s.name,role:s.role,ts:Date.now()});log(`Entrée session ${s.room} · ${s.role}`);applySavedIo();if(bgActive)showLiveNotification();qr();renderQuick()}else{log('Sortie de session');persistentNotification(false)}}const c=(api.getParticipants?.()||[]).length;if(lastCount&&c<lastCount)log(`Participant déconnecté · ${lastCount} → ${c}`);if(c!==lastCount){lastCount=c;decoratePeers();renderQuick()}}
function applySavedIo(){const out=localStorage.fosa_out_enabled,inn=localStorage.fosa_in_enabled,mic=localStorage.fosa_mic_enabled;if(out!=null)api.setOut(out==='1');if(inn!=null)api.setIn(inn==='1');if(mic!=null)api.setMic(mic==='1')}
function persistIo(){const s=state();localStorage.fosa_out_enabled=s.outEnabled?'1':'0';localStorage.fosa_in_enabled=s.inEnabled?'1':'0';localStorage.fosa_mic_enabled=s.micEnabled?'1':'0'}
function renderDiagSimple(){const src=$('#audioLat'),dst=$('#v080Quality');if(!src||!dst)return;const m=parseInt(src.textContent||'');let q='EN ATTENTE',cls='';if(Number.isFinite(m)){q=m<60?'EXCELLENT':m<120?'BON':'INSTABLE';cls=m<120?'on':'warn'}dst.textContent=q;dst.className='v080-badge '+cls}
function buildUI(){restoreQuery();syncRoleOptions();setMode(mode);setLock(liveLocked);bgActive=load('fosa_background_mode',false);
const setup=$$('.setupOnly')[0];if(setup){const p=document.createElement('section');p.className='card setupOnly';p.innerHTML=`<h2>Test avant live</h2><div class="v080-preflight-meter" id="v080Meter"><i></i></div><div class="row" style="margin-top:8px"><button id="v080Preflight" type="button">TEST MICRO & RÉSEAU</button><span id="v080PreflightStatus" class="small">Vérification recommandée avant un concert.</span></div>`;setup.after(p);$('#v080Preflight').onclick=preflight}
const live=$('.livePage');if(live){const q=document.createElement('section');q.id='v080QuickTalk';q.className='livePage';q.innerHTML=`<div class="v080-row" style="justify-content:space-between;align-items:center"><span id="v080Quality" class="v080-badge">EN ATTENTE</span><button id="v080CallChef" class="v080-chip call" type="button">APPELER CHEF</button></div><div class="v080-quick-scroll" id="v080QuickTargets" style="margin-top:6px"></div>`;live.before(q);$('#v080CallChef').onclick=callChef}
const lock=document.createElement('button');lock.id='v080Lock';lock.className='v080-lock';lock.type='button';lock.onclick=()=>setLock(!liveLocked);document.body.appendChild(lock);setLock(liveLocked);
const menu=$('.menuPage');if(menu){const m=document.createElement('section');m.className='card menuPage';m.innerHTML=`<h2>FOSA v${VERSION} · Live control</h2><div class="v080-grid"><button data-usage-mode="rehearsal">RÉPÉTITION</button><button data-usage-mode="concert">CONCERT</button></div><div class="v080-row" style="margin-top:8px"><button id="v080Bg">ARRIÈRE-PLAN</button><button id="v080AutoRejoin">AUTO-RECONNEXION</button><button id="v080FavCurrent">★ DESTINATION</button></div><p id="v080BgNote" class="v080-note"></p><div id="v080Qr" style="display:flex;justify-content:center;margin:10px 0"></div><div class="v080-title">Favoris rapides</div><div class="v080-row" id="v080Favorites"></div>`;menu.after(m);
const g=document.createElement('section');g.className='card menuPage';g.innerHTML=`<h2>Rôles & groupes</h2><div class="v080-grid"><input id="v080RoleName" placeholder="Nouveau rôle"><button id="v080AddRole">AJOUTER RÔLE</button></div><div class="v080-grid" style="margin-top:8px"><input id="v080GroupName" placeholder="Nom du groupe"><button id="v080AddGroup">CRÉER GROUPE</button></div><div id="v080RoleChecks" class="v080-row" style="margin-top:8px"></div><div id="v080Groups" style="margin-top:8px"></div><div class="v080-title" style="margin-top:12px">Ordre de priorité</div><div class="v080-grid"><input id="v080Priority" placeholder="Chef, Sono" value="${esc((load('fosa_priority_roles',['Chef','Sono'])).join(', '))}"><button id="v080SavePriority">ENREGISTRER PRIORITÉ</button></div><p class="v080-note">Le premier rôle a la priorité la plus élevée. Les autres flux sont atténués lorsqu’un rôle prioritaire parle.</p>`;m.after(g);
const a=document.createElement('section');a.className='card menuPage';a.innerHTML=`<h2>Administration & sécurité</h2><div class="v080-admin"><span id="v080AdminState" class="v080-badge warn">ADMIN VERROUILLÉ</span><div class="v080-grid"><input id="v080Pin" type="password" inputmode="numeric" placeholder="PIN administrateur"><button id="v080Unlock">DÉVERROUILLER</button></div><div class="v080-row"><button id="v080SetPin">DÉFINIR / CHANGER PIN</button><button id="v080RemoteAllowed">CONTRÔLE DISTANT ON</button></div><p class="v080-note">Le PIN protège surtout contre les mauvaises manipulations dans la session. Il ne remplace pas une authentification serveur.</p></div>`;g.after(a);
const h=document.createElement('section');h.className='card menuPage';h.innerHTML=`<h2>Historique de session</h2><div id="v080History" class="v080-history"></div><button id="v080ClearHistory" style="margin-top:8px">EFFACER HISTORIQUE</button>`;a.after(h)}
$$('[data-usage-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.usageMode));$('#v080Bg')?.addEventListener('click',()=>persistentNotification(!bgActive));$('#v080AutoRejoin')?.addEventListener('click',()=>{const on=localStorage.fosa_auto_rejoin!=='1';localStorage.fosa_auto_rejoin=on?'1':'0';updateToggleLabels()});$('#v080FavCurrent')?.addEventListener('click',addFavoriteCurrent);$('#v080AddRole')?.addEventListener('click',()=>{const v=$('#v080RoleName').value.trim();if(!v)return;if(!customRoles.includes(v))customRoles.push(v);save('fosa_custom_roles',customRoles);$('#v080RoleName').value='';syncRoleOptions();toast('Rôle ajouté',v)});$('#v080AddGroup')?.addEventListener('click',()=>{const name=$('#v080GroupName').value.trim(),roles=$$('#v080RoleChecks input:checked').map(x=>x.value);if(!name||!roles.length){toast('Groupe incomplet','Choisissez un nom et au moins un rôle.');return}customGroups=customGroups.filter(g=>g.name.toLowerCase()!==name.toLowerCase());customGroups.push({name,roles});save('fosa_custom_groups',customGroups);$('#v080GroupName').value='';renderGroups()});$('#v080Groups')?.addEventListener('click',e=>{const b=e.target.closest('[data-del-group]');if(!b)return;customGroups.splice(Number(b.dataset.delGroup),1);save('fosa_custom_groups',customGroups);renderGroups()});$('#v080Favorites')?.addEventListener('click',e=>{const b=e.target.closest('[data-remove-fav]');if(!b)return;favorites=favorites.filter(f=>f.target!==b.dataset.removeFav);save('fosa_favorites',favorites);renderFavorites();renderQuick()});$('#v080SavePriority')?.addEventListener('click',()=>{const roles=$('#v080Priority').value.split(',').map(x=>x.trim()).filter(Boolean);if(!roles.length)return;save('fosa_priority_roles',roles);toast('Priorités enregistrées',roles.join(' > '));log('Priorités: '+roles.join(' > '))});$('#v080SetPin')?.addEventListener('click',setPin);$('#v080Unlock')?.addEventListener('click',unlockPin);$('#v080RemoteAllowed')?.addEventListener('click',()=>{localStorage.fosa_allow_remote_control=localStorage.fosa_allow_remote_control==='0'?'1':'0';updateToggleLabels()});$('#v080ClearHistory')?.addEventListener('click',()=>{history=[];save('fosa_history',history);renderHistory()});updateToggleLabels();updateBackgroundUi();renderFavorites();renderGroups();renderHistory();renderQuick();updateAdmin()}
function updateToggleLabels(){const ar=$('#v080AutoRejoin');if(ar){const on=localStorage.fosa_auto_rejoin==='1';ar.classList.toggle('active',on);ar.textContent='AUTO-RECONNEXION '+(on?'ON':'OFF')}const rr=$('#v080RemoteAllowed');if(rr){const on=localStorage.fosa_allow_remote_control!=='0';rr.classList.toggle('active',on);rr.textContent='CONTRÔLE DISTANT '+(on?'ON':'OFF')}}
function wire(){window.addEventListener('fosa-control',e=>handleControl(e.detail));document.addEventListener('pointerdown',e=>{const b=e.target.closest?.('[data-qtarget]');if(b){e.preventDefault();pressTarget(b)}},{passive:false});document.addEventListener('pointerup',releaseTarget);document.addEventListener('pointercancel',releaseTarget);document.addEventListener('click',e=>{const b=e.target.closest?.('[data-remote]');if(b){const rid=b.dataset.rid,key=b.dataset.remote,rs=remoteStates.get(rid)||{mic:true,input:true,output:true};rs[key]=!rs[key];remoteStates.set(rid,rs);sendRemote(rid,key,rs[key]);decoratePeers()}});$('#outToggle')?.addEventListener('click',()=>setTimeout(persistIo));$('#inToggle')?.addEventListener('click',()=>setTimeout(persistIo));$('#micToggle')?.addEventListener('click',()=>setTimeout(persistIo));$('#postNav')?.addEventListener('click',e=>{if(liveLocked&&e.target.closest('[data-page="menu"]')){e.stopImmediatePropagation();e.preventDefault();toast('LIVE verrouillé','Déverrouillez avec le cadenas pour ouvrir le menu.')}},true);$('#leave')?.addEventListener('click',e=>{if(liveLocked){e.stopImmediatePropagation();e.preventDefault();toast('LIVE verrouillé','Déverrouillez avant de quitter la session.')}},true);$('#menuLeave')?.addEventListener('click',e=>{if(liveLocked){e.stopImmediatePropagation();e.preventDefault();toast('LIVE verrouillé','Déverrouillez avant de quitter la session.')}},true);addEventListener('online',()=>log('Réseau disponible'));addEventListener('offline',()=>log('Réseau perdu'));document.addEventListener('visibilitychange',()=>{if(document.hidden&&state().joined&&bgActive)showLiveNotification();if(!document.hidden&&state().joined)log('Retour au premier plan')});setInterval(()=>{updateJoinState();renderDiagSimple();decoratePeers()},1000)}
function boot(){api=window.FOSA_API;if(!api){setTimeout(boot,80);return}buildUI();wire();autoRejoin();log('FOSA v'+VERSION+' chargé')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot));else setTimeout(boot);
})();