// Real HTTP coordinator requests and real Chromium Opus/DTLS/SRTP. The room is
// a protocol fixture; Android tests exercise the production Kotlin coordinator.
const {chromium}=require('playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),out=process.env.FOSA_BROWSER_OUTPUT||'/tmp/fosa-local-check';fs.mkdirSync(out,{recursive:true});
const hostId='00000000-0000-0000-0000-000000000000',sessionId='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',code='482731';
const members=[{id:hostId,name:'ZO',role:'HOST',leader:true,group:'BAND',online:true,generation:1,token:'host-private-test-token',canTalk:true,canListen:true}];
const mail=new Map(),challenges=new Set(),requests=[];let serial=0;
const room=(name,q,token)=>{
 if(name==='info')return {protocol:'FOSA-LAN/2',protocolVersion:2,session:sessionId,sessionName:'BAND LIVE',code,hostName:'ZO',hostRole:'HOST',members:members.length,internetRequired:false};
 if(name==='challenge'){const nonce=crypto.randomBytes(16).toString('hex');challenges.add(nonce);return {nonce,session:sessionId};}
 if(name==='join'){assert.equal(q.code,code);assert.equal(q.session,sessionId);assert(challenges.delete(q.nonce),'One-use local auth challenge');let m=members.find(m=>m.key===q.clientKey);if(m){m.generation++;mail.set(m.id,[]);}else {m={id:crypto.randomUUID(),token:crypto.randomBytes(32).toString('hex'),key:q.clientKey,name:q.name,role:q.role,group:'BAND',online:true,generation:1,canTalk:true,canListen:true};members.push(m);}return {...m,session:sessionId,sessionName:'BAND LIVE',leader:hostId};}
 const m=members.find(m=>m.token===token);assert(m,'Authenticated API');
 if(name==='poll'){m.talk=!!q.talk;m.target=q.target;const queue=mail.get(m.id)||[];mail.set(m.id,queue.filter(s=>s.seq>q.after));return {members:members.map(({token,key,...u})=>u),signals:queue.filter(s=>s.seq>q.after),session:sessionId,sessionName:'BAND LIVE'};}
 if(name==='signal'){const queue=mail.get(q.to)||[];queue.push({seq:++serial,from:m.id,generation:m.generation,type:q.type,data:q.data});mail.set(q.to,queue);return {ok:true};}
 if(name==='leave'){members.splice(members.indexOf(m),1);return {ok:true};}throw Error('Unexpected RPC '+name);
};
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/lan/')){let bytes='';for await(const b of req)bytes+=b;assert(bytes.length<32768);const name=u.pathname.slice(5);requests.push(name);res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(room(name,JSON.parse(bytes||'{}'),(req.headers.authorization||'').replace('Bearer ',''))));}
 const name=u.pathname==='/'?'index.html':u.pathname.slice(1),file=path.join(root,name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||name.startsWith('tests/')){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({js:'text/javascript',html:'text/html',css:'text/css',svg:'image/svg+xml',json:'application/json'})[name.split('.').pop()]||'text/plain');res.end(fs.readFileSync(file));}catch(e){res.writeHead(400,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message}));}});
// Chrome feeds this WAV through getUserMedia, AudioWorklet and the production
// processing chain. No replacement of microphone, senders or decoded tracks.
const wav=path.join(out,'microphone-input.wav');{
 const rate=48000,n=rate*5,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++){const t=i/rate,amp=.22+.08*Math.sin(2*Math.PI*3*t);b.writeInt16LE(Math.round(amp*32767*(Math.sin(2*Math.PI*220*t)+.4*Math.sin(2*Math.PI*440*t))/.4/4),44+2*i);}fs.writeFileSync(wav,b);
}
const tone=async page=>{await page.evaluate(()=>fosaMobile.enableAudio());await page.waitForFunction(()=>fosaMobile.captureNonZeroFrames>4800&&fosaMobile.level>-65,null,{timeout:10000});};
const probe=async(page,id)=>page.evaluate(async id=>{const l=fosaMobile.links.get(id);const ctx=new AudioContext();await ctx.resume();const src=ctx.createMediaStreamSource(l.audio.srcObject),meter=ctx.createAnalyser();meter.fftSize=2048;src.connect(meter);window.rxProbe=ctx;window.rxRms=()=>{const a=new Float32Array(2048);meter.getFloatTimeDomainData(a);return Math.sqrt(a.reduce((s,v)=>s+v*v,0)/a.length);};},id);
(async()=>{let browser;try{await new Promise(r=>server.listen(0,'0.0.0.0',r));const origin=`http://127.0.0.1:${server.address().port}`;
 browser=await chromium.launch({executablePath:process.env.FOSA_CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox',`--use-file-for-fake-audio-capture=${wav}`,'--autoplay-policy=no-user-gesture-required','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});
 const contexts=await Promise.all([0,1].map(()=>browser.newContext({viewport:{width:390,height:844}})));const external=[];
 for(const c of contexts)await c.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin===origin)return route.continue();external.push(u.origin);return route.abort();});
 const [host,guest]=await Promise.all(contexts.map(c=>c.newPage()));await Promise.all([host,guest].map(p=>p.goto(origin)));
 await host.exposeFunction('coordinatorRPC',(id,p,b)=>room(p,b,members.find(m=>m.id===id)?.token));
 await host.evaluate(async({origin,hostId,sessionId})=>{const {FosaWebConnectionManager}=await import('./connection.js');const f=fosaMobile;f.profile={id:hostId,token:'host-private-test-token',name:'ZO',role:'HOST',leader:hostId,session:sessionId,sessionName:'BAND LIVE'};f.host=hostId;f.api=(path,body={})=>window.coordinatorRPC(hostId,path,body);f.wire=(l,dc)=>{l.channel=dc;dc.onopen=()=>f.changed();dc.onmessage=async e=>{const q=JSON.parse(e.data),id=[...f.links].find(([,v])=>v===l)?.[0];try{const data=await window.coordinatorRPC(id,q.path,q.body);dc.send(JSON.stringify({requestId:q.requestId,data}));}catch(e){dc.send(JSON.stringify({requestId:q.requestId,error:e.message}));}};};f.localConnection=new FosaWebConnectionManager(origin);await f.microphoneReady();f.loop=setInterval(()=>f.poll(),500);await f.poll();},{origin,hostId,sessionId});await tone(host);
 await guest.click('#join');await guest.fill('[name="code"]',code);await guest.fill('[name="name"]','JOHN');await guest.click('#join-form button');
 await guest.waitForFunction(()=>fosaMobile.directReady()&&fosaMobile.members.length===2,null,{timeout:25000});await guest.waitForFunction(()=>[...fosaMobile.links.values()].every(l=>!!l.audio),null,{timeout:10000});
 const guestId=await guest.evaluate(()=>fosaMobile.profile.id);await probe(guest,hostId);await host.evaluate(()=>fosaMobile.push(true));await guest.waitForFunction(()=>rxRms()>.01,null,{timeout:10000});await host.evaluate(()=>fosaMobile.push(false));await guest.waitForFunction(()=>rxRms()<.005,null,{timeout:10000});
 await host.waitForFunction(()=>[...fosaMobile.links.values()].some(l=>!!l.audio),null,{timeout:10000});await probe(host,guestId);await tone(guest);await guest.locator('#ptt').scrollIntoViewIfNeeded();const box=await guest.locator('#ptt').boundingBox();await guest.mouse.move(box.x+box.width/2,box.y+box.height/2);await guest.mouse.down();await host.waitForFunction(()=>rxRms()>.01,null,{timeout:10000});await guest.mouse.up();await host.waitForFunction(()=>rxRms()<.005,null,{timeout:10000});
 // TAP is controlled by the rendered button: pointer release must not close it.
 await guest.locator('#mode-TAP').click();await guest.locator('#ptt').click();
 await host.waitForFunction(()=>rxRms()>.003,null,{timeout:10000});
 for(let i=0;i<12;i++){await guest.waitForTimeout(15000);assert(await guest.evaluate(()=>fosaMobile.talkControl.armed&&fosaMobile.talking),'TAP stays open for three real minutes');assert(await host.evaluate(()=>rxRms()>.003),'Decoded PCM remains nonzero during prolonged TAP');}
 console.log('PASS real getUserMedia PCM and three-minute TAP with continuous decoded remote audio');
 await guest.locator('#ptt').click();await host.waitForFunction(()=>rxRms()<.005,null,{timeout:10000});
 // Panic, permission revocation and reconnect must not reopen a latched mic.
 await guest.locator('#ptt').click();await guest.locator('#panic').click();await guest.locator('#panic').click();assert.equal(await guest.evaluate(()=>fosaMobile.talkControl.armed),false);
 await guest.locator('#ptt').click();members.find(m=>m.id===guestId).canTalk=false;await guest.waitForFunction(()=>!fosaMobile.talkControl.armed);members.find(m=>m.id===guestId).canTalk=true;await guest.waitForTimeout(1000);assert.equal(await guest.evaluate(()=>fosaMobile.talkControl.armed),false);
 await guest.evaluate(async()=>{fosaMobile.push(true);await fosaMobile.signal(fosaMobile.host,'reset',{});await fosaMobile.receive({from:fosaMobile.host,type:'reset',data:{}});});await guest.waitForFunction(()=>fosaMobile.directReady(),null,{timeout:25000});assert.equal(await guest.evaluate(()=>fosaMobile.talkControl.armed),false);
 await probe(host,guestId);await guest.evaluate(()=>fosaMobile.testAudio());await host.waitForFunction(()=>rxRms()>.003,null,{timeout:10000});await host.waitForFunction(()=>rxRms()<.005,null,{timeout:10000});assert.equal(await guest.evaluate(()=>fosaMobile.talkRequested),false);
 await guest.locator('#mode-HOLD').click();
 await guest.evaluate(()=>fosaMobile.stats());const metrics=await guest.evaluate(()=>[...fosaMobile.links.values()].map(l=>l.metrics));assert(metrics.every(m=>m.localCandidateType==='host'&&m.peerCandidateType==='host'&&m.dtls==='connected'),'Selected pair must be local host/host with DTLS connected');assert(metrics.every(m=>Number.isFinite(m.rttMs)));
 const mediaConfig=await guest.evaluate(()=>[...fosaMobile.links.values()].map(l=>l.pc.getConfiguration()));assert(mediaConfig.every(c=>!c.iceServers.length));assert(!requests.some(p=>/audio|media/i.test(p)));assert.deepEqual(external,[]);
 const old=await guest.evaluate(()=>({id:fosaMobile.profile.id,generation:fosaMobile.profile.generation}));await guest.goto(origin+'/?'+new URLSearchParams({c:code,s:sessionId,name:'JOHN',join:'1'}));await guest.waitForFunction(()=>fosaMobile.directReady(),null,{timeout:25000});assert.equal(await guest.evaluate(()=>fosaMobile.profile.id),old.id);assert.equal(members.length,2);assert.equal(await guest.evaluate(()=>fosaMobile.profile.generation),old.generation+1);
 const before=await guest.evaluate(()=>/a=ice-ufrag:([^\r\n]+)/.exec(fosaMobile.links.get(fosaMobile.host).pc.localDescription.sdp)[1]);await guest.evaluate(()=>fosaMobile.repairAudio());await guest.waitForFunction(()=>fosaMobile.directReady()&&fosaMobile.links.get(fosaMobile.host).pc.signalingState==='stable',null,{timeout:15000});const after=await guest.evaluate(()=>/a=ice-ufrag:([^\r\n]+)/.exec(fosaMobile.links.get(fosaMobile.host).pc.localDescription.sdp)[1]);assert.notEqual(before,after);
 await guest.click('[data-tab="STATUS"]');await guest.screenshot({path:path.join(out,'local-first-status.png')});await guest.click('[data-tab="TALK"]');await guest.screenshot({path:path.join(out,'local-first-talk.png')});
 // Three simultaneous speakers: six real local audio directions.
 const thirdContext=await browser.newContext({viewport:{width:390,height:844}});await thirdContext.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const third=await thirdContext.newPage();await third.goto(origin);await third.click('#join');await third.fill('[name="code"]',code);await third.fill('[name="name"]','MILA');await third.click('#join-form button');
 await third.waitForFunction(()=>fosaMobile.links.size===2&&[...fosaMobile.links.values()].every(l=>l.pc.connectionState==='connected'),null,{timeout:25000});
 await Promise.all([host,guest,third].map(p=>p.evaluate(()=>{fosaMobile.setMode('TAP');fosaMobile.push(true);})));await third.waitForTimeout(5000);
 const mesh=[];for(const p of [host,guest,third]){await p.evaluate(()=>fosaMobile.stats());const d=await p.evaluate(()=>fosaMobile.diagnostics());assert(d.captureNonZeroFrames>4800);assert.equal(d.links.length,2);assert(d.links.every(l=>l.bytesSent>0&&l.bytesReceived>0&&l.totalAudioEnergy>0&&l.receiveDbfs>-65),'Each of six directions must carry nonzero decoded PCM');mesh.push(d);}
 console.log('FOSA_THREE_SPEAKER_PCM',JSON.stringify(mesh.map(d=>({captureFrames:d.captureFrames,captureNonZeroFrames:d.captureNonZeroFrames,links:d.links.map(l=>({bytesSent:l.bytesSent,bytesReceived:l.bytesReceived,totalAudioEnergy:l.totalAudioEnergy,receiveDbfs:l.receiveDbfs}))}))));await Promise.all([host,guest,third].map(p=>p.evaluate(()=>fosaMobile.push(false))));
 await third.evaluate(()=>fosaMobile.disconnect());await thirdContext.close();await guest.waitForFunction(()=>fosaMobile.members.length===2);await guest.evaluate(()=>fosaMobile.setMode('HOLD'));await host.evaluate(()=>fosaMobile.setMode('HOLD'));
 // Entire TCP coordinator can disappear after pairing. RPC and audio survive
 // on the encrypted local data channel, independent of WAN/DNS/Supabase/GitHub.
 await Promise.all(contexts.map(c=>c.route('**/lan/**',r=>r.abort())));await host.evaluate(()=>fosaMobile.push(true));await probe(guest,hostId);await guest.waitForFunction(()=>rxRms()>.01,null,{timeout:10000});await host.evaluate(()=>fosaMobile.push(false));await guest.waitForFunction(()=>rxRms()<.005,null,{timeout:10000});assert.equal(await guest.evaluate(()=>fosaMobile.error),'');
 fs.writeFileSync(path.join(out,'local-first-results.json'),JSON.stringify({version:'0.14.0',requests,selectedPairs:metrics,externalRequests:external,decodedAudioBothDirections:true,resumeWithoutDuplicate:true,shortQrRedirectAutoJoin:true,iceRestart:true,fixture:'Node protocol coordinator; real Chromium WebRTC with WAV through getUserMedia and production AudioWorklet',capturePath:'getUserMedia → PCM meter → HPF/compressor → sender → Opus → remote decoder',tapContinuousSeconds:180,simultaneousSpeakers:3,meshDirections:6,mesh,panicAndPermissionNeverRearm:true,explicitDiagnosticTone:true,capture:await guest.evaluate(()=>fosaMobile.diagnostics())},null,2));
 console.log('PASS local-first: code join with real HTTP, one-use challenge, real getUserMedia PCM and bidirectional decoded Opus, held PTT, three-minute TAP, Panic/permissions/reconnect no rearm, explicit diagnostic tone, host/host ICE + DTLS, zero external requests, resume same identity, ICE restart, control/audio surviving loss of coordinator HTTP. Physical Wi-Fi/P2P and Android Web origin require separate tests.');
 }finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
