// Real HTTP coordinator requests and real Chromium Opus/DTLS/SRTP. The room is
// a protocol fixture; Android tests exercise the production Kotlin coordinator.
const {chromium}=require('playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),out=process.env.FOSA_BROWSER_OUTPUT||'/tmp/fosa-local-check';fs.mkdirSync(out,{recursive:true});
const hostId='00000000-0000-0000-0000-000000000000',sessionId='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',code='482731';
const members=[{id:hostId,name:'ZO',role:'HOST',leader:true,group:'BAND',online:true,generation:1,token:'host-private-test-token',canTalk:true,canListen:true}];
const mail=new Map(),challenges=new Set(),requests=[];let serial=0;
const room=(name,q,token)=>{
 if(name==='info')return {protocol:'FOSA-LAN/2',protocolVersion:2,session:sessionId,sessionName:'BAND LIVE',code,hostName:'ZO',hostRole:'HOST',members:members.length,internetRequired:false};
 if(name==='challenge'){const nonce=crypto.randomBytes(16).toString('hex');challenges.add(nonce);return {nonce,session:sessionId};}
 if(name==='join'){assert.equal(q.code,code);assert.equal(q.session,sessionId);assert(challenges.delete(q.nonce),'One-use local auth challenge');let m=members.find(m=>m.key===q.clientKey);if(m){m.generation++;mail.set(m.id,[]);}else {m={id:crypto.randomUUID(),token:crypto.randomBytes(32).toString('hex'),key:q.clientKey,name:q.name,role:q.role,group:'BAND',online:true,generation:1,canTalk:true,canListen:true};members.push(m);}return {...m,session:sessionId,sessionName:'BAND LIVE',leader:hostId};}
 const m=members.find(m=>m.token===token);assert(m,'Authenticated API');
 if(name==='poll'){m.talk=!!q.talk;m.target=q.target;const queue=mail.get(m.id)||[];mail.set(m.id,queue.filter(s=>s.seq>q.after));return {members:members.map(({token,key,...u})=>u),signals:queue.filter(s=>s.seq>q.after),session:sessionId,sessionName:'BAND LIVE'};}
 if(name==='signal'){const queue=mail.get(q.to)||[];queue.push({seq:++serial,from:m.id,generation:m.generation,type:q.type,data:q.data});mail.set(q.to,queue);return {ok:true};}
 if(name==='leave')return {ok:true};throw Error('Unexpected RPC '+name);
};
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/lan/')){let bytes='';for await(const b of req)bytes+=b;assert(bytes.length<32768);const name=u.pathname.slice(5);requests.push(name);res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(room(name,JSON.parse(bytes||'{}'),(req.headers.authorization||'').replace('Bearer ',''))));}
 const name=u.pathname==='/'?'index.html':u.pathname.slice(1),file=path.join(root,name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||name.startsWith('tests/')){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({js:'text/javascript',html:'text/html',css:'text/css',svg:'image/svg+xml',json:'application/json'})[name.split('.').pop()]||'text/plain');res.end(fs.readFileSync(file));}catch(e){res.writeHead(400,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message}));}});
const tone=async page=>page.evaluate(async()=>{const f=fosaMobile;await f.context?.resume();const ctx=new AudioContext();await ctx.resume();const osc=ctx.createOscillator(),gain=ctx.createGain(),dest=ctx.createMediaStreamDestination();osc.frequency.value=660;gain.gain.value=.15;osc.connect(gain).connect(dest);osc.start();window.testTone=ctx;f.microphone=dest.stream.getAudioTracks()[0];for(const l of f.links.values()){const track=f.microphone.clone();track.enabled=false;await l.pc.getSenders().find(s=>s.track?.kind==='audio')?.replaceTrack(track);l.track=track;}});
const probe=async(page,id)=>page.evaluate(async id=>{const l=fosaMobile.links.get(id);const ctx=new AudioContext();await ctx.resume();const src=ctx.createMediaStreamSource(l.audio.srcObject),meter=ctx.createAnalyser();meter.fftSize=2048;src.connect(meter);window.rxProbe=ctx;window.rxRms=()=>{const a=new Float32Array(2048);meter.getFloatTimeDomainData(a);return Math.sqrt(a.reduce((s,v)=>s+v*v,0)/a.length);};},id);
(async()=>{let browser;try{await new Promise(r=>server.listen(0,'0.0.0.0',r));const origin=`http://127.0.0.1:${server.address().port}`;
 browser=await chromium.launch({args:['--autoplay-policy=no-user-gesture-required','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});
 const contexts=await Promise.all([0,1].map(()=>browser.newContext({viewport:{width:390,height:844}})));const external=[];
 for(const c of contexts)await c.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin===origin)return route.continue();external.push(u.origin);return route.abort();});
 const [host,guest]=await Promise.all(contexts.map(c=>c.newPage()));await Promise.all([host,guest].map(p=>p.goto(origin)));
 await host.exposeFunction('coordinatorRPC',(id,p,b)=>room(p,b,members.find(m=>m.id===id)?.token));
 await host.evaluate(async({origin,hostId,sessionId})=>{const {FosaWebConnectionManager}=await import('./connection.js');const f=fosaMobile;f.profile={id:hostId,token:'host-private-test-token',name:'ZO',role:'HOST',leader:hostId,session:sessionId,sessionName:'BAND LIVE'};f.host=hostId;f.api=(path,body={})=>window.coordinatorRPC(hostId,path,body);f.wire=(l,dc)=>{l.channel=dc;dc.onopen=()=>f.changed();dc.onmessage=async e=>{const q=JSON.parse(e.data),id=[...f.links].find(([,v])=>v===l)?.[0];try{const data=await window.coordinatorRPC(id,q.path,q.body);dc.send(JSON.stringify({requestId:q.requestId,data}));}catch(e){dc.send(JSON.stringify({requestId:q.requestId,error:e.message}));}};};f.localConnection=new FosaWebConnectionManager(origin);await f.microphoneReady();f.loop=setInterval(()=>f.poll(),500);await f.poll();},{origin,hostId,sessionId});await tone(host);
 await guest.click('#join');await guest.fill('[name="code"]',code);await guest.fill('[name="name"]','JOHN');await guest.click('#join-form button');
 await guest.waitForFunction(()=>fosaMobile.directReady()&&fosaMobile.members.length===2,null,{timeout:25000});await guest.waitForFunction(()=>[...fosaMobile.links.values()].every(l=>!!l.audio),null,{timeout:10000});
 const guestId=await guest.evaluate(()=>fosaMobile.profile.id);await probe(guest,hostId);await host.evaluate(()=>fosaMobile.push(true));await guest.waitForFunction(()=>rxRms()>.01,null,{timeout:10000});await host.evaluate(()=>fosaMobile.push(false));await guest.waitForFunction(()=>rxRms()<.005,null,{timeout:10000});
 await host.waitForFunction(()=>[...fosaMobile.links.values()].some(l=>!!l.audio),null,{timeout:10000});await probe(host,guestId);await tone(guest);await guest.locator('#ptt').scrollIntoViewIfNeeded();const box=await guest.locator('#ptt').boundingBox();await guest.mouse.move(box.x+box.width/2,box.y+box.height/2);await guest.mouse.down();await host.waitForFunction(()=>rxRms()>.01,null,{timeout:10000});await guest.mouse.up();await host.waitForFunction(()=>rxRms()<.005,null,{timeout:10000});
 await guest.evaluate(()=>fosaMobile.stats());const metrics=await guest.evaluate(()=>[...fosaMobile.links.values()].map(l=>l.metrics));assert(metrics.every(m=>m.localCandidateType==='host'&&m.peerCandidateType==='host'&&m.dtls==='connected'),'Selected pair must be local host/host with DTLS connected');assert(metrics.every(m=>Number.isFinite(m.rttMs)));
 const mediaConfig=await guest.evaluate(()=>[...fosaMobile.links.values()].map(l=>l.pc.getConfiguration()));assert(mediaConfig.every(c=>!c.iceServers.length));assert(!requests.some(p=>/audio|media/i.test(p)));assert.deepEqual(external,[]);
 const old=await guest.evaluate(()=>({id:fosaMobile.profile.id,generation:fosaMobile.profile.generation}));await guest.goto(origin+'/?'+new URLSearchParams({c:code,s:sessionId,name:'JOHN',join:'1'}));await guest.waitForFunction(()=>fosaMobile.directReady(),null,{timeout:25000});assert.equal(await guest.evaluate(()=>fosaMobile.profile.id),old.id);assert.equal(members.length,2);assert.equal(await guest.evaluate(()=>fosaMobile.profile.generation),old.generation+1);
 const before=await guest.evaluate(()=>/a=ice-ufrag:([^\r\n]+)/.exec(fosaMobile.links.get(fosaMobile.host).pc.localDescription.sdp)[1]);await guest.evaluate(()=>fosaMobile.repairAudio());await guest.waitForFunction(()=>fosaMobile.directReady()&&fosaMobile.links.get(fosaMobile.host).pc.signalingState==='stable',null,{timeout:15000});const after=await guest.evaluate(()=>/a=ice-ufrag:([^\r\n]+)/.exec(fosaMobile.links.get(fosaMobile.host).pc.localDescription.sdp)[1]);assert.notEqual(before,after);
 await guest.click('[data-tab="STATUS"]');await guest.screenshot({path:path.join(out,'local-first-status.png')});await guest.click('[data-tab="TALK"]');await guest.screenshot({path:path.join(out,'local-first-talk.png')});
 // Entire TCP coordinator can disappear after pairing. RPC and audio survive
 // on the encrypted local data channel, independent of WAN/DNS/Supabase/GitHub.
 await Promise.all(contexts.map(c=>c.route('**/lan/**',r=>r.abort())));await host.evaluate(()=>fosaMobile.push(true));await probe(guest,hostId);await guest.waitForFunction(()=>rxRms()>.01,null,{timeout:10000});await host.evaluate(()=>fosaMobile.push(false));await guest.waitForFunction(()=>rxRms()<.005,null,{timeout:10000});assert.equal(await guest.evaluate(()=>fosaMobile.error),'');
 fs.writeFileSync(path.join(out,'local-first-results.json'),JSON.stringify({version:'0.14.0',requests,selectedPairs:metrics,externalRequests:external,decodedAudioBothDirections:true,resumeWithoutDuplicate:true,shortQrRedirectAutoJoin:true,iceRestart:true,fixture:'Node protocol coordinator; real Chromium WebRTC'},null,2));
 console.log('PASS local-first: code join with real HTTP, one-use challenge, real bidirectional decoded Opus, held PTT, host/host ICE + DTLS, zero external requests, resume same identity, ICE restart, control/audio surviving loss of coordinator HTTP. Physical Wi-Fi/P2P and Android Web origin require separate tests.');
 }finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
