import {WebLanClient} from './core.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(id,text,secondary=true)=>`<button id="${id}" class="${secondary?'secondary':''}">${text}</button>`;
const label=s=>`<span class="label">${s}</span>`,panel=s=>`<section class="panel">${s}</section>`;
let tab='HOME',rendered='',scanner=null,live=localStorage.getItem('fosa-performance')==='1';
const client=new WebLanClient(()=>{draw();update();});window.fosaMobile=client;
const content=$('#content'),sheet=$('#sheet');sheet.querySelector('.close').onclick=()=>{scanner?.stop();sheet.close();};sheet.addEventListener('close',()=>scanner?.stop());
function bind(id,fn){const e=$('#'+id);if(e)e.onclick=fn;}
function modal(html){$('#sheet-content').innerHTML=html;sheet.showModal();}
function showError(e){modal(`<h2>Connection help</h2><p class="warning">${esc(e.message||e)}</p>`);}
function nav(){const n=$('#nav');n.hidden=!client.profile;if(!client.profile)return;n.innerHTML=['TALK','MEMBERS','STATUS','SETTINGS'].map(t=>`<button data-tab="${t}" class="${tab===t?'active':''}">${t}</button>`).join('');n.querySelectorAll('button').forEach(b=>b.onclick=()=>{client.push(false);tab=b.dataset.tab;draw(true);});}
function draw(force=false){const active=!!client.profile;if(active&&tab==='HOME')tab='TALK';const key=tab+active;if(rendered===key&&!force)return;rendered=key;nav();window.scrollTo(0,0);
  if(tab==='HOME'){content.innerHTML=`<div class="hero">${label('PRIVATE NETWORK INTERCOM')}<h1>Your stage.<br>Your connection.</h1><p>Le réseau local vous relie.<br>Internet n’est pas requis pendant la session.</p></div><div class="grid">${panel(`${label('01 / NATIVE APP · RECOMMENDED')}<h2>Create a session</h2><p>Le téléphone Android accueille votre groupe. Audio natif et écoute en arrière-plan.</p><a href="https://github.com/ZoNampoina/fosa/releases/download/android-latest/FOSA-Android.apk">Download Android APK</a>`)}${panel(`${label('02 / WEB FALLBACK')}<h2>Join your band</h2><p>Android, iPhone, tablette ou PC. Gardez la page ouverte pour l’audio.</p>${button('join','JOIN SESSION',false)}`)}</div>${panel(`${label('OFFLINE PACKAGE')}<p>Chargez cette page une fois avant de couper Internet.</p>${button('offline','CHECK OFFLINE READY')}`)}<footer><span class="status">LOCAL NETWORK · NO CLOUD AUDIO</span><p class="subtle">FOSA Mobile Web 0.11.0 · Compatibility mode</p></footer>`;bind('join',joinForm);bind('offline',offline);return;}
  if(tab==='TALK'){content.innerHTML=`<div class="grid talk-grid"><div><div class="hero">${label(esc(client.profile.sessionName))}<h1>${esc(client.profile.name)}<br><span style="color:var(--muted)">${esc(client.profile.role)}</span></h1><div class="row spread"><span class="status" id="session-status">CONNECTING</span><span class="label" id="member-count"></span></div></div>${panel(`${label('OUTPUT')}<h3>System audio route</h3><p>Préférez des écouteurs filaires / USB. Bluetooth ajoute de la latence.</p>${label('AUDIO LATENCY')}<div class="numeric">UNKNOWN</div>`).replace('class="panel"','class="panel audio-summary"')}<div id="talking-members"></div></div><div class="talk">${label('TALK TO')}<div class="row full">${['ALL','GROUP','LEADER','USER'].map(t=>button('to-'+t,t)).join('')}</div><b id="destination" style="color:var(--accent)">ALL</b><button id="ptt" class="talk-circle"><em>◉</em><b>HOLD TO TALK</b><small>Release to listen</small></button><div class="meter"><i id="mic-meter"></i></div>${label('MIC INPUT · MEASURED')}${button('enable','ENABLE AUDIO')}${button('panic','PANIC MUTE')}</div></div>`;
    for(const t of ['ALL','GROUP','LEADER','USER'])bind('to-'+t,()=>{if(t==='USER'||t==='GROUP')destination(t);else client.destination(t.toLowerCase());});
    const ptt=$('#ptt');ptt.onpointerdown=e=>{if(!client.microphone){showError(client.micError||'Microphone unavailable');return;}if(![...client.links.values()].some(l=>l.pc.connectionState==='connected'))return;e.preventDefault();ptt.setPointerCapture(e.pointerId);if(localStorage.getItem('fosa-haptic')!=='0')navigator.vibrate?.(15);client.push(true);};ptt.onpointerup=ptt.onpointercancel=ptt.onlostpointercapture=()=>client.push(false);bind('panic',()=>client.panic(!client.muted));bind('enable',()=>client.enableAudio().catch(showError));
  }else if(tab==='MEMBERS'){content.innerHTML=`<h1>Your band</h1><span class="label">PRIVATE LAN SESSION</span><div id="member-list" class="grid" style="margin-top:20px"></div>`;
  }else if(tab==='STATUS'){content.innerHTML=`<h1>Session health</h1><div class="grid">${panel(`${label('LOCAL NETWORK')}<span class="status" id="session-status">CONNECTING</span>${label('SESSION')}<h3>${esc(client.profile.sessionName)}</h3>${label('INTERNET')}<h3>Not required</h3>${label('AUDIO LATENCY')}<div class="numeric">UNKNOWN</div><p>Le RTT ne mesure pas la latence micro → écouteurs.</p>`)}${panel(`${label('DIRECT AUDIO LINKS')}<div id="metrics"></div>`)}</div>${button('advanced','ADVANCED DIAGNOSTICS')}`;bind('advanced',diagnostics);
  }else {content.innerHTML=`<h1>Make it yours</h1><div class="grid">${panel(`${label('AUDIO')}<div class="field"><span class="label">TALKBACK VOLUME</span><input id="volume" type="range" min="0" max="1" step=".01" value="${client.master}" aria-label="Talkback volume"></div><p>HPF, voice compressor, browser echo cancellation / noise suppression. Personnalisation du gate / EQ : non disponible.</p>`)}${panel(`${label('LIVE')}<label class="switch">Performance mode<input id="performance" type="checkbox" ${live?'checked':''}></label><label class="switch">Haptic feedback<input id="haptic" type="checkbox" ${localStorage.getItem('fosa-haptic')!=='0'?'checked':''}></label><p class="subtle">Arrière-plan Web non garanti. Native Android recommandé pour Live.</p>`)}${panel(`${label('APP')}<label class="field"><span class="label">Theme</span><select id="theme"><option>DARK</option><option>LIGHT</option><option>SYSTEM</option></select></label>${button('offline','OFFLINE PACKAGE')}${button('advanced','ADVANCED DIAGNOSTICS')}${label('FOSA MOBILE WEB · 0.11.0')}`)}${panel(`${label('SESSION')}${button('leave','LEAVE SESSION')}`)}</div>`;$('#volume').oninput=e=>client.volume(Number(e.target.value));$('#performance').onchange=e=>{live=e.target.checked;localStorage.setItem('fosa-performance',live?'1':'0');};$('#haptic').onchange=e=>localStorage.setItem('fosa-haptic',e.target.checked?'1':'0');$('#theme').value=localStorage.getItem('fosa-theme')||'DARK';$('#theme').onchange=e=>{localStorage.setItem('fosa-theme',e.target.value);theme();};bind('offline',offline);bind('advanced',diagnostics);bind('leave',()=>{client.api('leave').catch(()=>{});client.close();client.profile=null;tab='HOME';draw(true);});}
  update();
}
function member(u){return panel(`<div class="row member"><div class="avatar">${esc(u.name.slice(0,2).toUpperCase())}</div><div class="identity"><h3>${esc(u.name)}</h3><small>${esc(u.role||'MEMBER')}</small></div><span class="status">${u.talk?'TALKING':u.online?'LOCAL':'OFFLINE'}</span></div><div class="meter"><i style="width:${u.talk&&Number.isFinite(u.level)?Math.max(0,Math.min(100,(u.level+60)/60*100)):0}%"></i></div>${label('GROUP · '+esc(u.group||'BAND'))}${u.id!==client.profile.id?`<div class="row"><button class="secondary" data-user="${esc(u.id)}">TALK</button><button class="secondary" data-mute="${esc(u.id)}">${client.mutes.has(u.id)?'UNMUTE':'MUTE'}</button></div>`:''}`);}
function update(){if(!client.profile)return;$('#connection').textContent=client.talking?'TALK':client.error?'RECONNECTING':'LOCAL';const status=$('#session-status');if(status)status.textContent=[...client.links.values()].some(l=>l.pc.connectionState==='connected')?'SRTP CONNECTED':'CONNECTING';if($('#member-count'))$('#member-count').textContent=client.members.length+' MEMBERS';if($('#destination'))$('#destination').textContent=client.target.startsWith('user:')?client.members.find(m=>m.id===client.target.slice(5))?.name||'Member':client.target.toUpperCase();const ptt=$('#ptt');if(ptt){ptt.classList.toggle('transmitting',client.talking);ptt.querySelector('b').textContent=client.talking?'TALKING':'HOLD TO TALK';ptt.disabled=client.muted;$('#panic').textContent=client.muted?'UNMUTE':'PANIC MUTE';$('#mic-meter').style.width=client.talking&&Number.isFinite(client.level)&&!live?Math.max(0,(client.level+60)/60*100)+'%':'0%';$('#enable').hidden=!client.error;}
  const ml=$('#member-list')||$('#talking-members');if(ml){ml.innerHTML=client.members.filter(u=>tab==='MEMBERS'||u.talk&&u.id!==client.profile.id).slice(0,tab==='MEMBERS'?8:1).map(member).join('');ml.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>{client.destination('user:'+b.dataset.user);tab='TALK';draw(true);});ml.querySelectorAll('[data-mute]').forEach(b=>b.onclick=()=>{const muted=!client.mutes.has(b.dataset.mute);client.memberMute(b.dataset.mute,muted);b.textContent=muted?'UNMUTE':'MUTE';});}
  if($('#metrics'))$('#metrics').innerHTML=[...client.links.entries()].map(([id,l])=>`<h3>${esc(client.members.find(m=>m.id===id)?.name||'Member')}</h3><p class="numeric">${l.pc.connectionState.toUpperCase()}</p><p>RTT ${metric(l.metrics.rttMs,'ms')}<br>Jitter ${metric(l.metrics.jitterMs,'ms')}<br>Loss ${metric(l.metrics.loss,'%')}</p>`).join('<hr>');
}
function metric(v,u){return Number.isFinite(v)?v.toFixed(1)+' '+u+' · MEASURED':'UNKNOWN';}
function destination(type){const options=type==='USER'?client.members.filter(m=>m.id!==client.profile.id).map(m=>[m.id,m.name]):[...new Set(client.members.map(m=>m.group))].map(g=>[g,g]);modal(`<h2>Talk to ${type.toLowerCase()}</h2><div style="display:grid;gap:10px;margin-top:20px">${options.map(([id,name])=>`<button class="secondary" data-choice="${esc(id)}">${esc(name)}</button>`).join('')}</div>`);sheet.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{client.destination((type==='USER'?'user:':'group:')+b.dataset.choice);sheet.close();});}
function joinForm(){modal(`<h2>Join your band</h2><p>Le chef ouvre FOSA Native → Members → Web Pair.</p><form id="join-form"><label class="field">${label('YOUR NAME')}<input name="name" value="ZO" maxlength="40" required></label><label class="field">${label('ROLE / INSTRUMENT')}<input name="role" value="SAX" maxlength="40"></label><label class="field">${label('SESSION CODE')}<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required></label><button class="full" style="margin-top:16px">CREATE WEB INVITATION</button></form><p class="subtle">La PWA rejoint un hôte Android. Création d’un hôte Web : non disponible.</p>`);$('#join-form').onsubmit=async e=>{e.preventDefault();const form=e.target;form.querySelector('button').disabled=true;try{const url=await client.prepare(Object.fromEntries(new FormData(form)));modal(`<h2>Scan on the host phone</h2><p>Scannez ce QR sur le téléphone du chef, puis ouvrez FOSA.</p><canvas class="qr" id="invite-qr"></canvas><a id="native-link" href="${esc(url)}">Open in FOSA Native on this device</a><p>Puis scannez la réponse affichée par FOSA Native, depuis cette page.</p>${button('scan-answer','SCAN HOST ANSWER',false)}<label class="field">${label('OR PASTE ANSWER')}<textarea id="answer" rows="3"></textarea></label>${button('accept','CONNECT')}`);await FosaQR.draw($('#invite-qr'),url);bind('scan-answer',scanAnswer);bind('accept',()=>accept($('#answer').value));}catch(e){client.close();showError(e);}};}
async function scanAnswer(){try{const video=document.createElement('video');video.setAttribute('playsinline','');$('#sheet-content').prepend(video);scanner=await FosaQR.scan(video,text=>{scanner?.stop();video.remove();accept(text);});}catch(e){showError('Caméra indisponible. Copiez la réponse QR dans le champ.');}}
async function accept(value){try{await client.accept(value);localStorage.removeItem('fosa-answer');sheet.close();tab='TALK';draw(true);}catch(e){showError(e);}}
async function offline(){let ready=false;try{await Promise.race([navigator.serviceWorker?.ready,new Promise((_,reject)=>setTimeout(()=>reject(Error('Offline not ready')),4000))]);const c=await caches.open('fosa-mobile-0.11.0');ready=(await Promise.all(['./index.html','./style.css','./core.js','./app.js','./qr.js','./icon.svg','./manifest.json'].map(f=>c.match(new URL(f,location.href))))).every(Boolean);}catch{}modal(`<h2>Offline package</h2><p class="status">${ready?'READY':'NOT READY'}</p><p>App shell · Audio engine · UI · Icons</p><p>${ready?'Assets vérifiés dans le cache. Le LAN reste nécessaire pour l’audio.':'Rechargez cette page avec Internet et vérifiez à nouveau.'}</p>${button('recheck','CHECK OFFLINE READY')}`);bind('recheck',offline);}
function diagnostics(){modal(`<h2>Advanced diagnostics</h2><p>FOSA-LAN/1 · Opus 48 kHz<br>Direct WebRTC · DTLS/SRTP<br>No STUN / TURN / cloud relay<br>Audio latency UNKNOWN</p><p>Une coupure courte peut se rétablir automatiquement. Après changement d’adresse Wi-Fi ou fermeture du navigateur, refaire l’appairage QR.</p>`);}
function theme(){let t=localStorage.getItem('fosa-theme')||'DARK';if(t==='SYSTEM')t=matchMedia('(prefers-color-scheme:dark)').matches?'DARK':'LIGHT';document.documentElement.dataset.theme=t;}
window.addEventListener('pointerup',()=>client.push(false));window.addEventListener('pointercancel',()=>client.push(false));window.addEventListener('blur',()=>client.push(false));document.addEventListener('visibilitychange',()=>{if(document.hidden)client.push(false);});window.addEventListener('storage',e=>{if(e.key==='fosa-answer'&&e.newValue&&client.offer)accept(e.newValue);});
if(location.hash.startsWith('#answer=')){const value=location.hash.slice(8);localStorage.setItem('fosa-answer',value);history.replaceState(null,'',location.pathname);setTimeout(()=>{if(!client.offer)modal('<h2>Answer received</h2><p>Revenez à la page FOSA qui a créé l’invitation. Elle doit rester ouverte pendant l’appairage.</p>');},100);}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});theme();draw();
