import {WebLanClient} from './core.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(id,text,secondary=true)=>`<button id="${id}" class="${secondary?'secondary':''}">${text}</button>`;
const label=s=>`<span class="label">${s}</span>`,panel=s=>`<section class="panel">${s}</section>`;
let tab='HOME',rendered='',scanner=null,live=localStorage.getItem('fosa-performance')==='1';
const client=new WebLanClient(()=>{draw();update();});window.fosaMobile=client;
const content=$('#content'),sheet=$('#sheet');sheet.querySelector('.close').onclick=()=>{scanner?.stop();sheet.close();};sheet.addEventListener('close',()=>{scanner?.stop();if(!client.profile&&client.offer)client.close();});
function bind(id,fn){const e=$('#'+id);if(e)e.onclick=fn;}
function modal(html){$('#sheet-content').innerHTML=html;if(!sheet.open)sheet.showModal();}
function showError(e){modal(`<h2>Connection help</h2><p class="warning">${esc(e.message||e)}</p>`);}
function nav(){const n=$('#nav');n.hidden=!client.profile;if(!client.profile)return;n.innerHTML=['TALK','MEMBERS','STATUS','SETTINGS'].map(t=>`<button data-tab="${t}" class="${tab===t?'active':''}">${t}</button>`).join('');n.querySelectorAll('button').forEach(b=>b.onclick=()=>{client.push(false);tab=b.dataset.tab;draw(true);});}
function draw(force=false){const active=!!client.profile;if(active&&tab==='HOME')tab='TALK';if(!active)tab='HOME';const key=tab+active;if(rendered===key&&!force)return;rendered=key;nav();window.scrollTo(0,0);
  if(tab==='HOME'){content.innerHTML=`<div class="hero">${label('PRIVATE NETWORK INTERCOM')}<h1>Your stage.<br>Your connection.</h1><p>Audio et contrôle restent sur le réseau local.<br>Le mode Web par code utilise Internet uniquement pour l’appairage initial.</p></div><div class="grid">${panel(`${label('01 / NATIVE APP · RECOMMENDED')}<h2>Create a session</h2><p>Le téléphone Android accueille votre groupe. Audio natif et écoute en arrière-plan.</p><a href="https://github.com/ZoNampoina/fosa/releases/download/android-latest/FOSA-Android.apk">Download Android APK</a>`)}${panel(`${label('02 / WEB FALLBACK')}<h2>Join your band</h2><p>Android, iPhone, tablette ou PC. Gardez la page ouverte pour l’audio.</p>${button('join','JOIN SESSION',false)}`)}</div>${panel(`${label('OFFLINE PACKAGE')}<p>Chargez cette page une fois avant de couper Internet.</p>${button('offline','CHECK OFFLINE READY')}`)}<footer><span class="status">LOCAL NETWORK · NO CLOUD AUDIO</span><p class="subtle">FOSA Mobile Web 0.12.7 · Compatibility mode</p></footer>`;bind('join',()=>joinForm());bind('offline',offline);return;}
  if(tab==='TALK'){content.innerHTML=`<div class="grid talk-grid"><div><div class="hero">${label(esc(client.profile.sessionName))}<h1>${esc(client.profile.name)}<br><span style="color:var(--muted)">${esc(client.profile.role)}</span></h1><div class="row spread"><span class="status" id="session-status">CONNECTING</span><span class="label" id="member-count"></span></div></div>${panel(`${label('OUTPUT')}<h3>System audio route</h3><p>Préférez des écouteurs filaires / USB. Bluetooth ajoute de la latence.</p>${label('AUDIO LATENCY')}<div class="numeric">UNKNOWN</div>`).replace('class="panel"','class="panel audio-summary"')}<div id="talking-members"></div></div><div class="talk">${label('TALK TO')}<div class="row full">${['ALL','GROUP','LEADER','USER'].map(t=>button('to-'+t,t)).join('')}</div><b id="destination" style="color:var(--accent)">ALL</b><button id="listen" class="secondary">LISTEN · ALL</button><button id="ptt" class="talk-circle"><em>◉</em><b>HOLD TO TALK</b><small>Release to listen</small></button><div class="meter"><i id="mic-meter"></i></div>${label('MIC INPUT · MEASURED')}${button('enable','ENABLE AUDIO')}${button('repair','RECONNECT AUDIO',true)}${button('panic','PANIC MUTE')}</div></div>`;
    for(const t of ['ALL','GROUP','LEADER','USER'])bind('to-'+t,()=>{if(t==='USER'||t==='GROUP')destination(t);else client.destination(t.toLowerCase());});
    const ptt=$('#ptt');ptt.onpointerdown=e=>{if(!client.microphone){showError(client.micError||'Microphone unavailable');return;}e.preventDefault();ptt.setPointerCapture(e.pointerId);client.enableAudio().catch(()=>{});if(localStorage.getItem('fosa-haptic')!=='0')navigator.vibrate?.(15);client.push(true);};ptt.onpointerup=ptt.onpointercancel=ptt.onlostpointercapture=()=>client.push(false);ptt.onkeydown=e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();if(!e.repeat){client.enableAudio().catch(()=>{});client.push(true);}}};ptt.onkeyup=e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();client.push(false);}};ptt.onblur=()=>client.push(false);bind('listen',()=>listenDestination());bind('panic',()=>client.panic(!client.muted));bind('enable',()=>client.enableMicrophone().catch(showError));bind('repair',async()=>{try{await client.repairAudio();}catch(e){if((e.message||e)==='DIRECT_LINK_LOST')repairSession();else showError(e);}});
  }else if(tab==='MEMBERS'){content.innerHTML=`<h1>Your band</h1><span class="label">PRIVATE LAN SESSION</span><div id="member-list" class="grid" style="margin-top:20px"></div>`;
  }else if(tab==='STATUS'){content.innerHTML=`<h1>Session health</h1><div class="grid">${panel(`${label('LOCAL NETWORK')}<span class="status" id="session-status">CONNECTING</span>${label('SESSION')}<h3>${esc(client.profile.sessionName)}</h3>${label('INTERNET')}<h3>Not required</h3>${label('AUDIO LATENCY')}<div class="numeric">UNKNOWN</div><p>Le RTT ne mesure pas la latence micro → écouteurs.</p>`)}${panel(`${label('DIRECT AUDIO LINKS')}<div id="metrics"></div>`)}</div>${button('advanced','ADVANCED DIAGNOSTICS')}`;bind('advanced',diagnostics);
  }else {content.innerHTML=`<h1>Make it yours</h1><div class="grid">${panel(`${label('AUDIO')}<div class="field"><span class="label">TALKBACK VOLUME</span><input id="volume" type="range" min="0" max="1" step=".01" value="${client.master}" aria-label="Talkback volume"></div><p>HPF, voice compressor, browser echo cancellation / noise suppression. Personnalisation du gate / EQ : non disponible.</p>`)}${panel(`${label('LIVE')}<label class="switch">Performance mode<input id="performance" type="checkbox" ${live?'checked':''}></label><label class="switch">Haptic feedback<input id="haptic" type="checkbox" ${localStorage.getItem('fosa-haptic')!=='0'?'checked':''}></label><p class="subtle">Arrière-plan Web non garanti. Native Android recommandé pour Live.</p>`)}${panel(`${label('APP')}<label class="field"><span class="label">Theme</span><select id="theme"><option>DARK</option><option>LIGHT</option><option>SYSTEM</option></select></label>${button('offline','OFFLINE PACKAGE')}${button('advanced','ADVANCED DIAGNOSTICS')}${label('FOSA MOBILE WEB · 0.12.7')}`)}${panel(`${label('SESSION')}${button('leave','LEAVE SESSION')}`)}</div>`;$('#volume').oninput=e=>client.volume(Number(e.target.value));$('#performance').onchange=e=>{live=e.target.checked;localStorage.setItem('fosa-performance',live?'1':'0');};$('#haptic').onchange=e=>localStorage.setItem('fosa-haptic',e.target.checked?'1':'0');$('#theme').value=localStorage.getItem('fosa-theme')||'DARK';$('#theme').onchange=e=>{localStorage.setItem('fosa-theme',e.target.value);theme();};bind('offline',offline);bind('advanced',diagnostics);bind('leave',async()=>{const button=$('#leave');button.disabled=true;await client.disconnect();tab='HOME';draw(true);});}
  update();
}
function member(u){return panel(`<div class="row member"><div class="avatar">${esc(u.name.slice(0,2).toUpperCase())}</div><div class="identity"><h3>${esc(u.name)}</h3><small>${esc(u.role||'MEMBER')}</small></div><span class="status">${u.talk?'TALKING':u.online?'LOCAL':'OFFLINE'}</span></div><div class="meter"><i style="width:${u.talk&&Number.isFinite(u.level)?Math.max(0,Math.min(100,(u.level+60)/60*100)):0}%"></i></div>${label('GROUP · '+esc(u.group||'BAND'))}${u.id!==client.profile.id?`<div class="row"><button class="secondary" data-user="${esc(u.id)}">TALK</button><button class="secondary" data-mute="${esc(u.id)}">${client.mutes.has(u.id)?'UNMUTE':'MUTE'}</button></div>`:''}`);}
function update(){if(!client.profile)return;const ready=[...client.links.values()].some(l=>l.pc.connectionState==='connected'),hostReady=client.host?client.links.get(client.host)?.pc.connectionState==='connected':false;$('#connection').textContent=client.talking?'TALK':client.error||!hostReady?'RECONNECTING':'LOCAL';const status=$('#session-status');if(status)status.textContent=hostReady?'SRTP CONNECTED':'CONNECTING';if($('#member-count'))$('#member-count').textContent=client.members.length+' MEMBERS';if($('#destination'))$('#destination').textContent=client.target.startsWith('user:')?client.members.find(m=>m.id===client.target.slice(5))?.name||'Member':client.target.toUpperCase();if($('#listen')){const t=client.listenTarget||'all';$('#listen').textContent='LISTEN · '+(t.startsWith('user:')?client.members.find(m=>m.id===t.slice(5))?.name||'USER':t.startsWith('group:')?t.slice(6):t.toUpperCase());}const ptt=$('#ptt');if(ptt){const requesting=client.talkRequested&&!client.talking;ptt.classList.toggle('transmitting',client.talking);ptt.classList.toggle('requesting',requesting);ptt.querySelector('b').textContent=client.talking?'TALKING':requesting?'CONNECTING…':'HOLD TO TALK';ptt.disabled=client.muted;$('#panic').textContent=client.muted?'UNMUTE':'PANIC MUTE';$('#mic-meter').style.width=client.talking&&Number.isFinite(client.level)&&!live?Math.max(0,(client.level+60)/60*100)+'%':'0%';ptt.querySelector('small').textContent=!client.microphone?'Active le microphone ci-dessous':requesting?'Garde le doigt appuyé · liaison audio en cours':!ready?'Audio non connecté · maintiens pour réessayer':client.talking?'Relâche pour écouter':'Maintiens le bouton pour parler';$('#enable').textContent=client.microphone?'ENABLE / UNLOCK AUDIO':'ENABLE MICROPHONE';$('#enable').hidden=!!client.microphone&&client.context?.state==='running'&&[...client.links.values()].every(l=>!l.audioPending)&&!client.error;if($('#repair'))$('#repair').hidden=hostReady&&!client.error;}
  const ml=$('#member-list')||$('#talking-members');if(ml){ml.innerHTML=client.members.filter(u=>tab==='MEMBERS'||u.talk&&u.id!==client.profile.id).slice(0,tab==='MEMBERS'?8:1).map(member).join('');ml.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>{client.destination('user:'+b.dataset.user);tab='TALK';draw(true);});ml.querySelectorAll('[data-mute]').forEach(b=>b.onclick=()=>{const muted=!client.mutes.has(b.dataset.mute);client.memberMute(b.dataset.mute,muted);b.textContent=muted?'UNMUTE':'MUTE';});}
  if($('#metrics'))$('#metrics').innerHTML=[...client.links.entries()].map(([id,l])=>`<h3>${esc(client.members.find(m=>m.id===id)?.name||'Member')}</h3><p class="numeric">${l.pc.connectionState.toUpperCase()}</p><p>ICE ${esc(String(l.iceState||l.pc.iceConnectionState||'unknown').toUpperCase())} · candidates ${l.localCandidates||0}/${l.remoteCandidates||0}<br>Audio ${l.audioPending?'LOCKED · TAP ENABLE AUDIO':l.audio?'READY':'WAITING'}<br>RTT ${metric(l.metrics.rttMs,'ms')}<br>Jitter ${metric(l.metrics.jitterMs,'ms')}<br>Loss ${metric(l.metrics.loss,'%')}</p>`).join('<hr>');
}
function metric(v,u){return Number.isFinite(v)?v.toFixed(1)+' '+u+' · MEASURED':'UNKNOWN';}
function destination(type){const options=type==='USER'?client.members.filter(m=>m.id!==client.profile.id).map(m=>[m.id,m.name]):[...new Set(client.members.map(m=>m.group))].map(g=>[g,g]);modal(`<h2>Talk to ${type.toLowerCase()}</h2><div style="display:grid;gap:10px;margin-top:20px">${options.map(([id,name])=>`<button class="secondary" data-choice="${esc(id)}">${esc(name)}</button>`).join('')}</div>`);sheet.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{client.destination((type==='USER'?'user:':'group:')+b.dataset.choice);sheet.close();});}function listenDestination(){const buttons=[['all','ALL']];if(client.profile?.id!==client.profile?.leader)buttons.push(['leader','LEADER']);for(const g of [...new Set(client.members.map(m=>m.group).filter(Boolean))])buttons.push(['group:'+g,'GROUP · '+g]);for(const m of client.members.filter(m=>m.id!==client.profile.id))buttons.push(['user:'+m.id,'USER · '+m.name]);modal(`<h2>Listen to</h2><div style="display:grid;gap:10px;margin-top:20px">${buttons.map(([id,name])=>`<button class="secondary" data-listen="${esc(id)}">${esc(name)}</button>`).join('')}</div>`);sheet.querySelectorAll('[data-listen]').forEach(b=>b.onclick=()=>{client.listen(b.dataset.listen);sheet.close();});}

const RENDEZVOUS="https://kgrrxhmzteefmdbgdbaf.supabase.co/functions/v1/pair-rendezvous",RENDEZVOUS_KEY="sb_publishable_xWl3rWRXfTrL9WGERJmkHQ_Gnjz8bv3";
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function rendezvous(action,body={},timeout=6000){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),timeout);try{const r=await fetch(RENDEZVOUS,{method:"POST",headers:{"content-type":"application/json",apikey:RENDEZVOUS_KEY},body:JSON.stringify({action,...body}),cache:"no-store",signal:ctrl.signal});const q=await r.json().catch(()=>({error:"Réponse rendez-vous illisible"}));if(!r.ok||q.error)throw Error(q.error||"Rendez-vous indisponible");return q;}catch(e){if(e?.name==="AbortError"||e instanceof TypeError)throw Error("RENDEZVOUS_OFFLINE");throw e;}finally{clearTimeout(timer);}}
async function pairByCode(values){
  if(globalThis.FOSA_DISABLE_RENDEZVOUS===true||navigator.onLine===false)return showOfflineInvite(values,"Internet indisponible : passage automatique en appairage 100 % local.");
  let started=null,lastStartError=null;
  for(let attempt=0;attempt<8&&!started;attempt++){try{started=await rendezvous("guest-offer",{code:values.code,offer:client.offer,name:values.name,role:values.role});}catch(e){lastStartError=e;if((e.message||e)==="RENDEZVOUS_OFFLINE")return showOfflineInvite(values,"Rendez-vous Internet indisponible : FOSA bascule automatiquement en mode 100 % local.");if((e.message||e)!=="Session unavailable")throw e;if(attempt<7)await sleep(450);}}
  if(!started)throw lastStartError||Error("Session unavailable");
  const deadline=Date.now()+30000;let accepted=false,lastAnswer="";
  while(Date.now()<deadline){
    const q=await rendezvous("guest-poll",{code:values.code,id:started.id});
    if(q.answer&&q.answer!==lastAnswer){
      lastAnswer=q.answer;
      if(!accepted){await client.accept(q.answer);accepted=true;}
      else await client.refreshPair(q.answer);
    }
    if(accepted&&client.directReady()){sheet.close();tab="TALK";draw(true);return;}
    await sleep(450);
  }
  if(accepted){client.close();client.profile=null;}
  throw Error("Le code a été trouvé, mais la liaison audio locale n’a pas pu s’établir. Vérifie le même Wi-Fi/hotspot et désactive l’isolation des clients.");
}
function joinForm(values={name:"ZO",role:"SAX",code:""},failure="",allowOffline=true){
  modal(`<h2>Rejoindre une session</h2><p><b>Code :</b> Internet sert uniquement à l’appairage initial, puis audio et contrôle restent sur le LAN. <b>Sans Internet :</b> utilise le QR local.</p><form id="join-form" novalidate><label class="field">${label("SESSION CODE · 6 CHIFFRES")}<input name="code" value="${esc(values.code)}" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="482731" aria-describedby="code-help join-error" required></label><p id="code-help" class="subtle">Sur l’hôte Android, ouvre MEMBERS → CODE / QR : cela affiche le code et ouvre temporairement l’appairage Web.</p><label class="field">${label("YOUR NAME")}<input name="name" value="${esc(values.name)}" maxlength="40" required></label><label class="field">${label("ROLE / INSTRUMENT")}<input name="role" value="${esc(values.role)}" maxlength="40"></label><p id="join-error" class="warning" role="alert" ${failure?"":"hidden"}>${esc(failure)}</p><p id="join-progress" role="status" hidden>Recherche de la session et appairage sécurisé… Aucun scan nécessaire.</p><button class="full" style="margin-top:16px">JOIN WITH CODE · INITIAL INTERNET</button>${allowOffline?`<button id="offline-pair" type="button" class="secondary full" style="margin-top:10px">100% LOCAL · OFFLINE QR</button>`:""}</form>`);
  const form=$("#join-form"),error=$("#join-error");
  form.elements.code.oninput=e=>e.target.value=e.target.value.replace(/\D/g,"").slice(0,6);
  form.oninput=()=>{error.hidden=true;for(const field of form.querySelectorAll("input"))field.removeAttribute("aria-invalid");};
  if(allowOffline)bind("offline-pair",()=>showOfflineInvite(values));
  form.onsubmit=async e=>{
    e.preventDefault();const values=Object.fromEntries(new FormData(form));for(const key of ["name","role","code"])values[key]=values[key].trim();
    const invalid=!values.name?"name":!/^[0-9]{6}$/.test(values.code)?"code":null;
    if(invalid){error.textContent=invalid==="code"?"Saisissez le code à 6 chiffres affiché par l’hôte.":"Indiquez votre nom pour rejoindre la session.";error.hidden=false;form.elements[invalid].setAttribute("aria-invalid","true");form.elements[invalid].focus();return;}
    if(client.offer)client.close();
    const submit=form.querySelector("button:not([type])");submit.disabled=true;submit.textContent="CONNECTING…";error.hidden=true;$("#join-progress").hidden=false;
    try{await client.prepare(values);await pairByCode(values);}catch(e){const keep=!!client.offer;let message=e.message||e;if(message==="Session unavailable")message="Sur l’hôte Android, ouvre MEMBERS → CODE / QR puis réessaie";joinForm(values,message+". "+(keep?"Tu peux aussi choisir 100% LOCAL · OFFLINE QR.":"Réessaie."),true);}
  };
}
function repairSession(){const values={name:client.profile?.name||"ZO",role:client.profile?.role||"",code:client.joinCode||""};client.close();client.profile=null;tab="HOME";draw(true);joinForm(values,"La liaison directe LAN a été perdue. Ré-appaire l’appareil : par code si Internet est disponible, ou par QR pour rester 100 % local.",true);}
async function showOfflineInvite(values,reason=""){
  try{
    if(!client.offer)await client.prepare(values);
    const url="fosa://mobile-pair?data="+client.offer,qr=document.createElement("canvas");qr.id="invite-qr";qr.className="qr";await FosaQR.draw(qr,url);
    modal(`<h2>Mode hors ligne · QR</h2>${reason?`<p class="status">${esc(reason)}</p>`:""}<p>Ce mode reste 100 % local : aucun Internet n’est nécessaire pour l’appairage ni pour l’audio.</p><div id="qr-slot"></div><p>Scannez ce QR sur le téléphone Android hôte, puis ouvrez FOSA → MEMBERS → WEB OFFLINE QR.</p><a id="native-link" href="${esc(url)}">Open invitation in FOSA Native</a><p>Scannez ensuite la réponse de l’hôte depuis cette page.</p>${button("scan-answer","SCAN HOST ANSWER",false)}<label class="field">${label("OR PASTE ANSWER")}<textarea id="answer" rows="3"></textarea></label>${button("accept","CONNECT")}${button("edit-invite","EDIT CODE / RETRY")}`);
    $("#qr-slot").replaceWith(qr);bind("scan-answer",scanAnswer);bind("accept",()=>accept($("#answer").value));bind("edit-invite",()=>{client.close();joinForm(values);});
  }catch(e){client.close();joinForm(values,"Impossible de préparer le mode QR : "+(e.message||e),false);}
}
async function scanAnswer(){try{const video=document.createElement('video');video.setAttribute('playsinline','');$('#sheet-content').prepend(video);scanner=await FosaQR.scan(video,text=>{scanner?.stop();video.remove();accept(text);});}catch(e){showError('Caméra indisponible. Copiez la réponse QR dans le champ.');}}
async function accept(value){try{await client.accept(value);localStorage.removeItem('fosa-answer');sheet.close();tab='TALK';draw(true);}catch(e){showError(e);}}
async function offline(){let ready=false;try{await Promise.race([navigator.serviceWorker?.ready,new Promise((_,reject)=>setTimeout(()=>reject(Error('Offline not ready')),4000))]);const c=await caches.open('fosa-mobile-0.12.7');ready=(await Promise.all(['./index.html','./style.css','./core.js','./app.js','./qr.js','./icon.svg','./manifest.json'].map(f=>c.match(new URL(f,location.href))))).every(Boolean);}catch{}modal(`<h2>Offline package</h2><p class="status">${ready?'READY':'NOT READY'}</p><p>App shell · Audio engine · UI · Icons</p><p>${ready?'Assets vérifiés dans le cache. Le LAN reste nécessaire pour l’audio.':'Rechargez cette page avec Internet et vérifiez à nouveau.'}</p>${button('recheck','CHECK OFFLINE READY')}`);bind('recheck',offline);}
function diagnostics(){const rows=[...client.links.entries()].map(([id,l])=>`${esc(client.members.find(m=>m.id===id)?.name||id)} · PC=${esc(l.pc.connectionState)} · ICE=${esc(l.iceState||l.pc.iceConnectionState)} · candidates=${l.localCandidates||0}/${l.remoteCandidates||0} · audio=${l.audioPending?'LOCKED':l.audio?'READY':'WAITING'}`).join('<br>');modal(`<h2>Advanced diagnostics</h2><p>FOSA-LAN/1 · Opus 48 kHz<br>Direct WebRTC · DTLS/SRTP<br>No STUN / TURN / cloud audio relay<br>Audio latency UNKNOWN</p><p>${rows||'No direct audio link yet.'}</p><p>Le rendez-vous Supabase transporte uniquement l’appairage initial du mode code. Dès que la liaison WebRTC est établie, l’audio et les commandes restent directs sur le LAN. Sans Internet, utilise le QR local. Si le lien direct est perdu après un changement réseau, un ré-appairage peut être nécessaire.</p>`);}
function theme(){let t=localStorage.getItem('fosa-theme')||'DARK';if(t==='SYSTEM')t=matchMedia('(prefers-color-scheme:dark)').matches?'DARK':'LIGHT';document.documentElement.dataset.theme=t;}
window.addEventListener('pointerdown',()=>{if(client.profile)client.enableAudio().catch(()=>{});},{passive:true});window.addEventListener('pointerup',()=>client.push(false));window.addEventListener('pointercancel',()=>client.push(false));window.addEventListener('blur',()=>client.push(false));document.addEventListener('visibilitychange',()=>{if(document.hidden)client.push(false);});window.addEventListener('storage',e=>{if(e.key==='fosa-answer'&&e.newValue&&client.offer)accept(e.newValue);});
if(location.hash.startsWith('#answer=')){const value=location.hash.slice(8);localStorage.setItem('fosa-answer',value);history.replaceState(null,'',location.pathname);setTimeout(()=>{if(!client.offer)modal('<h2>Answer received</h2><p>Revenez à la page FOSA qui a créé l’invitation. Elle doit rester ouverte pendant l’appairage.</p>');},100);}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});theme();draw();
