/* Discovery/authentication are independent of media. Browsers use the local
 * host origin; native adapters own DNS-SD and creation of Wi-Fi Direct groups. */
export const PHASES=Object.freeze(['DISCOVERING','FOUND','AUTHENTICATING','CONNECTING_NETWORK','SIGNALING','NEGOTIATING_AUDIO','CONNECTED','RECONNECTING','FAILED']);
export function discoveryMode(origin=location.origin){const u=new URL(origin);return u.protocol==='https:'&&u.hostname==='zonampoina.github.io'?'CLOUD_RENDEZVOUS':'LAN';}
export function sessionLocator(value){if(String(value).length>150)throw Error('Scanne le QR court de FOSA 0.13');const u=new URL(value);if(u.protocol!=='fosa:'||u.hostname!=='join'||u.searchParams.get('v')!=='2')throw Error('QR de session FOSA invalide');const code=u.searchParams.get('c'),host=u.searchParams.get('h'),session=u.searchParams.get('s');if(!/^[0-9]{6}$/.test(code)||!privateHost(host)||!/^[a-f0-9-]{6,40}$/i.test(session||''))throw Error('QR local invalide');return {code,session,origin:`https://${host}:48766`};}
export function privateHost(value){const n=String(value||'').split('.').map(x=>/^\d{1,3}$/.test(x)?Number(x):NaN);return n.length===4&&n.every(x=>Number.isInteger(x)&&x>=0&&x<=255)&&(n[0]===10||n[0]===192&&n[1]===168||n[0]===172&&n[1]>=16&&n[1]<=31);}
export class FosaWebConnectionManager {
  constructor(origin=location.origin,changed=()=>{}){this.origin=origin;this.changed=changed;this.phase='DISCOVERING';this.transport='Local Wi-Fi';}
  state(phase){if(!PHASES.includes(phase))throw Error('Invalid connection phase');this.phase=phase;this.changed();}
  async call(path,body={},token=''){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),3500);try{const r=await fetch(`${this.origin}/lan/${path}`,{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify(body),cache:'no-store',signal:ctrl.signal});const text=await r.text();if(text.length>32768)throw Error('Réponse locale trop grande');const q=JSON.parse(text);if(!r.ok||q.error)throw Error(q.error||'Hôte inaccessible');return q;}finally{clearTimeout(timer);}}
  async discover(){this.state('DISCOVERING');try{const info=await this.call('info');if(!/^FOSA-LAN\//.test(info.protocol)||!info.session)throw Error('Session FOSA non trouvée');this.info=info;this.transport=info.transportLabel||'Local Wi-Fi';this.state('FOUND');return info;}catch{this.state('FAILED');throw Error('Ouvre WEB ACCESS sur l’hôte et utilise son lien local. Le navigateur peut rejoindre ce réseau ; l’application native détecte les sessions à proximité.');}}
  async join(values,identity){const info=this.info||await this.discover();if(values.session&&values.session!==info.session)throw Error('La session de ce QR a expiré');if(values.code!==info.code)throw Error('Code session incorrect');this.state('AUTHENTICATING');const nonce=await this.call('challenge');const profile=await this.call('join',{...values,session:info.session,protocolVersion:2,nonce:nonce.nonce,client:'Local Web',clientKey:identity.clientKey,resumeToken:identity.profile?.token||''});this.state('SIGNALING');return profile;}
}
