import {TalkControl} from './talk.js';
/* FOSA-LAN/1: local WebRTC Opus audio and authenticated coordinator RPC. */
const privateV6 = value => {const v=String(value||'').split('%')[0].toLowerCase();return v.startsWith('fc')||v.startsWith('fd')||/^fe[89ab]/.test(v);};
export const lanCandidate = c => {const p=String(c||'').trim().split(/\s+/),n=p[4]?.split('.').map(Number);return p.length>7&&p[6]==='typ'&&p[7]==='host'&&(p[4]?.endsWith('.local')||privateV6(p[4])||n?.length===4&&n.every(x=>Number.isInteger(x)&&x>=0&&x<=255)&&(n[0]===10||n[0]===192&&n[1]===168||n[0]===172&&n[1]>=16&&n[1]<=31));};
export const lanSdp = s => s.split('\r\n').filter(l=>!l.startsWith('a=candidate:')||lanCandidate(l.slice(2))).join('\r\n');
const sdpCandidates = s => new Set(String(s||'').split('\r\n').filter(l=>l.startsWith('a=candidate:')).map(l=>l.slice(2)));
export async function pack(value){const stream=new Blob([JSON.stringify(value)]).stream().pipeThrough(new CompressionStream('deflate'));const a=new Uint8Array(await new Response(stream).arrayBuffer());return btoa(String.fromCharCode(...a)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
export async function unpack(value){if(value.length>18000)throw Error('Invitation trop grande');const a=Uint8Array.from(atob(value.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));const stream=new Blob([a]).stream().pipeThrough(new DecompressionStream('deflate'));const reader=stream.getReader();let count=0;const chunks=[];while(true){const {value,done}=await reader.read();if(done)break;count+=value.length;if(count>32768){await reader.cancel();throw Error('Invitation trop grande');}chunks.push(value);}return JSON.parse(await new Blob(chunks).text());}
const gather = pc => pc.iceGatheringState==='complete'?Promise.resolve():new Promise(resolve=>{const end=()=>{pc.removeEventListener('icegatheringstatechange',check);clearTimeout(timer);resolve();};const check=()=>{if(pc.iceGatheringState==='complete')end();};const timer=setTimeout(end,8000);pc.addEventListener('icegatheringstatechange',check);});
const resumeStore=code=>'fosa-lan-session:'+code;
function resumeIdentity(code){let saved;try{saved=JSON.parse(localStorage.getItem(resumeStore(code))||'null');}catch{}
  const clientKey=/^[a-f0-9]{32}$/.test(saved?.clientKey)?saved.clientKey:crypto.randomUUID().replaceAll('-','');
  const identity={clientKey,profile:saved?.profile};try{localStorage.setItem(resumeStore(code),JSON.stringify(identity));}catch{}return identity;
}
export class WebLanClient {
  constructor(changed=()=>{}){this.changed=changed;this.links=new Map();this.pending=new Map();this.serial=0;this.ack=0;this.members=[];this.target='all';this.listenTarget='all';this.talking=false;this.talkRequested=false;this.muted=false;this.master=.75;this.mutes=new Set();this.microphone=null;this.level=null;this.profile=null;this.error='';this.audioUnlocked=false;this.talkControl=new TalkControl();this.statsPoll=0;this.captureFrames=0;this.captureNonZeroFrames=0;this.captureAt=0;this.audioTick=setInterval(()=>this.audioHeartbeat(),100);this.repairAttempts=new Map();this.resumeAttempts=0;}
  async microphoneReady(){if(this.microphone)return;clearInterval(this.audioTick);this.audioTick=setInterval(()=>this.audioHeartbeat(),100);try{
    const raw=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:this.talkControl.noiseReduction,autoGainControl:true},video:false});this.raw=raw;
    const ctx=this.context=new AudioContext({latencyHint:'interactive',sampleRate:48000});await ctx.resume();
    const source=ctx.createMediaStreamSource(raw),hpf=ctx.createBiquadFilter(),compressor=ctx.createDynamicsCompressor(),dest=ctx.createMediaStreamDestination();hpf.type='highpass';hpf.frequency.value=100;compressor.threshold.value=-12;compressor.knee.value=4;compressor.ratio.value=12;compressor.attack.value=.003;compressor.release.value=.15;
    this.analyser=ctx.createAnalyser();this.analyser.fftSize=1024;source.connect(this.analyser);
    let capture=source;
    if(ctx.audioWorklet){await ctx.audioWorklet.addModule(new URL('./meter-worklet.js',import.meta.url));this.meterNode=new AudioWorkletNode(ctx,'fosa-meter',{numberOfInputs:1,numberOfOutputs:1,outputChannelCount:[1]});source.connect(this.meterNode);capture=this.meterNode;this.meterNode.port.onmessage=e=>{if(this.context!==ctx)return;this.captureFrames=e.data.frames;this.captureNonZeroFrames=e.data.nonzero;this.captureAt=Date.now();this.level=e.data.dbfs;};}
    capture.connect(hpf).connect(compressor).connect(dest);this.micDestination=dest;this.microphone=dest.stream.getAudioTracks()[0];
    raw.getAudioTracks()[0].onended=()=>{this.push(false);this.micError='Microphone arrêté : réactive son autorisation';this.changed();};this.micError='';
  }catch(e){this.raw?.getTracks().forEach(t=>t.stop());this.context?.close().catch(()=>{});this.raw=null;this.context=null;this.microphone=null;this.micError='Microphone bloqué : '+(e.message||e)+'. Écoute seule ; touche ENABLE MICROPHONE.';}}
  audioHeartbeat(){if(!this.profile&&!this.microphone)return;this.measureMic();const now=Date.now();this.talkControl.level(this.level,now);this.talkControl.tick(now);this.talkRequested=!!this.testTone||this.talkControl.requested;this.refreshTalk();}
  setMode(mode){this.stopTest();this.talkControl.setMode(mode);this.talkRequested=false;this.refreshTalk();}
  async audioOptions({threshold,closeDelayMs,timeoutMs,noiseReduction}={}){const c=this.talkControl;if(Number.isFinite(threshold))c.threshold=Math.max(-60,Math.min(-12,threshold));if(Number.isFinite(closeDelayMs))c.closeDelayMs=Math.max(150,Math.min(3000,closeDelayMs));if(Number.isFinite(timeoutMs)){c.timeoutMs=Math.max(0,Math.min(3600000,timeoutMs));if(c.armed&&c.mode!=='HOLD')c.deadline=Date.now()+(c.timeoutMs>0?c.timeoutMs:Infinity);}if(typeof noiseReduction==='boolean'){c.noiseReduction=noiseReduction;await this.raw?.getAudioTracks()[0]?.applyConstraints({noiseSuppression:noiseReduction});}this.changed();}
  diagnostics(){const now=Date.now(),links=[...this.links].map(([id,l])=>({id,...l.metrics,negotiationError:l.negotiationError||'',connection:l.pc.connectionState,signaling:l.pc.signalingState,senderEnabled:!!l.track?.enabled,receiveDbfs:l.receiveLevel??null,playbackBlocked:!!l.audioPending,playbackRunning:!!l.audio&&!l.audio.paused&&!l.audio.muted}));return {permission:this.raw?.getAudioTracks()[0]?.readyState||'not granted',captureSource:this.testTone?'EXPLICIT TEST SIGNAL':'MICROPHONE',capture:this.context?.state==='running'&&this.raw?.getAudioTracks()[0]?.readyState==='live'&&now-this.captureAt<1500,captureFrames:this.captureFrames,captureNonZeroFrames:this.captureNonZeroFrames,micDbfs:this.level,context:this.context?.state||'absent',mode:this.talkControl.mode,armed:this.talkControl.armed,transmission:this.talking&&links.some(l=>l.txPacketsDelta>0)?'SENDING':'IDLE',reception:links.some(l=>l.rxPacketsDelta>0&&(l.receiveDbfs??-120)>-90&&l.playbackRunning)?'RECEIVING':'WAITING',rxDbfs:Math.max(-120,...links.filter(l=>l.playbackRunning).map(l=>l.receiveDbfs??-120)),output:'System audio route',outputVolume:this.master,links};}
  async testAudio(){if(!this.microphone||this.muted||this.members.find(m=>m.id===this.profile?.id)?.canTalk===false)throw Error('Microphone autorisé et permission de parole requis');this.push(false);await this.enableAudio();const ctx=this.context,osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=660;gain.gain.value=.12;osc.connect(gain).connect(this.micDestination);osc.start();this.testTone=osc;this.talkRequested=true;this.refreshTalk();this.testTimer=setTimeout(()=>{this.stopTest();this.push(false);},2000);}
  stopTest(){if(this.testTone){this.testTone.stop();this.testTone.disconnect();this.testTone=null;}clearTimeout(this.testTimer);}
  async joinLocal(values,origin=location.origin){clearInterval(this.audioTick);this.audioTick=setInterval(()=>this.audioHeartbeat(),100);if(!/^[0-9]{6}$/.test(values.code||''))throw Error('Code de session à 6 chiffres requis');if(!String(values.name||'').trim())throw Error('Indique ton nom');if(!isSecureContext)throw Error('Le micro et la PWA exigent l’accès Web sécurisé de l’hôte. Ouvre /trust pour sa configuration.');const {FosaWebConnectionManager}=await import('./connection.js');this.joinCode=values.code;this.joinValues=values;this.resume=resumeIdentity(values.code);this.localConnection=new FosaWebConnectionManager(origin,()=>this.changed());this.profile=await this.localConnection.join(values,this.resume);this.host=this.profile.leader;this.ack=0;this.saveIdentity();await this.microphoneReady();this.localConnection.state('NEGOTIATING_AUDIO');this.loop=setInterval(()=>this.poll(),500);await this.poll();this.changed();}
  saveIdentity(){if(this.joinCode&&this.resume&&this.profile)try{localStorage.setItem(resumeStore(this.joinCode),JSON.stringify({clientKey:this.resume.clientKey,profile:this.profile}));}catch{}}
  async resumeLocal(){if(this.resumeAttempts>=6){this.error='Six reprises locales échouées. Vérifie le réseau et rejoins à nouveau avec la même identité.';this.changed();return;}if(!this.localConnection||this.resuming||Date.now()-(this.lastResume||0)<5000)return;this.resuming=true;this.resumeAttempts++;this.lastResume=Date.now();try{this.push(false);this.localConnection.state('RECONNECTING');this.localConnection.info=null;this.profile=await this.localConnection.join({...this.joinValues,session:this.profile.session},{...this.resume,profile:this.profile});this.host=this.profile.leader;this.ack=0;for(const id of this.links.keys())this.remove(id);this.saveIdentity();}finally{this.resuming=false;}}
  make(id,manual=false){if(this.links.has(id))return this.links.get(id);const pc=new RTCPeerConnection({iceServers:[],bundlePolicy:'max-bundle'});const link={pc,track:null,audio:null,audioPending:false,channel:null,remote:false,ice:[],localIce:[],remoteIce:new Set(),manual,generation:this.members.find(m=>m.id===id)?.generation??1,metrics:{},makingOffer:false,ignoreOffer:false,renegotiate:false,offerEpoch:0,negotiation:Promise.resolve(),iceState:'new',localCandidates:0,remoteCandidates:0};this.links.set(id,link);
    if(this.microphone){link.track=this.microphone.clone();link.track.enabled=false;pc.addTrack(link.track,new MediaStream([link.track]));}else pc.addTransceiver('audio',{direction:'recvonly'});
    pc.onicecandidate=e=>{if(this.links.get(id)===link&&e.candidate&&lanCandidate(e.candidate.candidate)){const q=e.candidate.toJSON();link.localIce.push(q);link.localCandidates=link.localIce.length;this.changed();if(!link.manual)this.signal(id,'ice',q).catch(()=>{});}};
    pc.oniceconnectionstatechange=()=>{link.iceState=pc.iceConnectionState;if(['disconnected','failed','closed'].includes(pc.iceConnectionState)&&this.talkControl.mode!=='HOLD')this.push(false);if(pc.iceConnectionState==='failed')this.repairAudio(false).catch(e=>{this.error=e.message;});this.refreshTalk();};
    pc.onconnectionstatechange=()=>{this.refreshTalk();};
    pc.ontrack=e=>{if(this.links.get(id)!==link)return;link.audio?.remove();const audio=document.createElement('audio');audio.autoplay=true;audio.setAttribute('playsinline','');audio.srcObject=e.streams[0]||new MediaStream([e.track]);audio.volume=this.master;audio.muted=this.muted||this.mutes.has(id)||!this.listenEligible(id);document.body.append(audio);link.audio=audio;if(this.context){link.receiveSource?.disconnect();link.receiveSource=this.context.createMediaStreamSource(audio.srcObject);link.receiveAnalyser=this.context.createAnalyser();link.receiveAnalyser.fftSize=1024;link.receiveSource.connect(link.receiveAnalyser);}const attempt=audio.play();if(attempt?.then)attempt.then(()=>{link.audioPending=false;this.changed();}).catch(()=>{link.audioPending=true;this.changed();});};
    pc.ondatachannel=e=>this.wire(link,e.channel);return link;
  }
  wire(link,c){link.channel=c;c.onmessage=e=>{try{const q=JSON.parse(e.data);const p=this.pending.get(q.requestId);if(p){clearTimeout(p.timer);this.pending.delete(q.requestId);q.error?p.reject(Error(q.error)):p.resolve(q.data);}}catch{}};c.onopen=()=>this.changed();}
  async prepare({name,role='',code}){name=String(name??'').trim();role=String(role).trim();code=String(code??'').trim();if(!name||name.length>40||role.length>40)throw Error('Nom ou instrument invalide');if(!/^[0-9]{6}$/.test(code))throw Error('Code de session à 6 chiffres requis');this.joinCode=code;this.resume=resumeIdentity(code);await this.microphoneReady();const l=this.make('host',true);this.wire(l,l.pc.createDataChannel('fosa-mobile'));await l.pc.setLocalDescription(await l.pc.createOffer());await gather(l.pc);const sdp=lanSdp(l.pc.localDescription.sdp),embedded=[...sdpCandidates(sdp)].filter(lanCandidate);if(!l.localIce.length&&!embedded.length)throw Error('Aucun candidat réseau local WebRTC disponible. Vérifie le Wi-Fi/hotspot et les protections WebRTC du navigateur.');this.offer=await pack({type:'offer',name,role,code,client:'Web fallback',clientKey:this.resume.clientKey,resumeToken:this.resume.profile?.token||'',sdp,ice:l.localIce});this.changed();return 'fosa://mobile-pair?data='+this.offer;}
  async accept(value){value=value.includes('#answer=')?value.split('#answer=')[1]:value.trim();const q=await unpack(value);if(q.type!=='answer'||!q.profile?.token)throw Error('Réponse QR invalide');const l=this.links.get('host');if(!l)throw Error('L’invitation a expiré. Crée une nouvelle invitation Web.');const embedded=sdpCandidates(q.sdp);await l.pc.setRemoteDescription({type:'answer',sdp:lanSdp(q.sdp)});this.profile=q.profile;this.host=q.host;this.links.delete('host');this.links.set(q.host,l);l.remote=true;l.remoteCandidates=Math.max(l.remoteCandidates,embedded.size);for(const candidate of q.ice||[])if(!embedded.has(candidate.candidate))await this.addRemoteIce(l,candidate);if(this.joinCode){try{localStorage.setItem(resumeStore(this.joinCode),JSON.stringify({clientKey:this.resume.clientKey,profile:q.profile}));}catch{}}this.loop=setInterval(()=>this.poll(),500);this.changed();}
  async refreshPair(value){value=value.includes('#answer=')?value.split('#answer=')[1]:value.trim();const q=await unpack(value);if(q.type!=='answer'||!q.profile?.token||q.host!==this.host||q.profile.id!==this.profile?.id)return;const l=this.links.get(this.host);if(!l)return;for(const candidate of q.ice||[])await this.addRemoteIce(l,candidate);this.changed();}
  directReady(){const l=this.links.get(this.host);return !!l&&l.pc.connectionState==='connected'&&l.channel?.readyState==='open';}
  forget(){if(this.joinCode)try{localStorage.removeItem(resumeStore(this.joinCode));}catch{}this.resume=null;}
  async disconnect(){this.push(false);let left=false;try{await this.api('leave');left=true;}catch{}if(left)this.forget();this.close();this.profile=null;}
  api(path,body={}){const c=this.links.get(this.host)?.channel;if(!c||c.readyState!=='open')return this.localConnection?this.localConnection.call(path,body,this.profile?.token||''):Promise.reject(Error('Connexion LAN en cours'));const requestId=++this.serial;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(requestId);reject(Error('Hôte local inaccessible'));},4000);this.pending.set(requestId,{resolve,reject,timer});c.send(JSON.stringify({requestId,path,body}));});}
  signal(to,type,data){return this.api('signal',{to,type,data});}
  enqueueNegotiation(l,action){const next=l.negotiation.catch(()=>{}).then(action);l.negotiation=next;return next;}
  async offerTo(id,iceRestart=false){const l=this.make(id);return this.enqueueNegotiation(l,async()=>{if(this.links.get(id)!==l)return;if(l.pc.signalingState!=='stable'){l.renegotiate=true;return;}l.makingOffer=true;const epoch=++l.offerEpoch;try{if(!l.channel)this.wire(l,l.pc.createDataChannel('fosa-mobile'));const offer=await l.pc.createOffer(iceRestart?{iceRestart:true}:undefined);if(epoch!==l.offerEpoch)return;l.negotiationError='';await l.pc.setLocalDescription(offer);await this.signal(id,'offer',{type:'offer',sdp:lanSdp(l.pc.localDescription.sdp)});}catch(e){l.negotiationError='Audio SDP offer: '+e.message;this.error=l.negotiationError;throw e;}finally{l.makingOffer=false;}});}
  async addRemoteIce(l,data){if(l.ignoreOffer||!data?.candidate||!lanCandidate(data.candidate))return;const key=[data.sdpMid??'',data.sdpMLineIndex??'',data.candidate].join('|');if(l.remoteIce.has(key))return;l.remoteIce.add(key);l.remoteCandidates=Math.max(l.remoteCandidates,l.remoteIce.size);if(l.remote)await l.pc.addIceCandidate(data);else l.ice.push(data);this.changed();}
  async receive({from,type,data}){if(type==='reset'){this.push(false);this.remove(from);this.make(from);if(this.profile.id<from)await this.offerTo(from);return;}const l=this.make(from);
    return this.enqueueNegotiation(l,async()=>{try{if(this.links.get(from)!==l)return;if(type==='ice'){await this.addRemoteIce(l,data);return;}if(!['offer','answer'].includes(type))return;if(type==='answer'&&l.pc.signalingState!=='have-local-offer')return;
      const collision=type==='offer'&&(l.makingOffer||l.pc.signalingState!=='stable');l.ignoreOffer=collision&&this.profile.id<from;if(l.ignoreOffer)return;
      if(collision){++l.offerEpoch;l.renegotiate=true;if(l.pc.signalingState==='have-local-offer')await l.pc.setLocalDescription({type:'rollback'});}
      l.negotiationError='';const embedded=sdpCandidates(data.sdp);await l.pc.setRemoteDescription({type,sdp:lanSdp(data.sdp)});l.remote=true;l.remoteCandidates=Math.max(l.remoteCandidates,embedded.size);for(const c of l.ice)await l.pc.addIceCandidate(c);l.ice=[];
      if(type==='offer'){await l.pc.setLocalDescription(await l.pc.createAnswer());await this.signal(from,'answer',{type:'answer',sdp:lanSdp(l.pc.localDescription.sdp)});}
      if(l.renegotiate&&l.pc.signalingState==='stable'){l.renegotiate=false;queueMicrotask(()=>this.offerTo(from).catch(e=>{this.error=e.message;this.changed();}));}
    }catch(e){l.negotiationError='Audio SDP '+type+': '+e.message;this.error=l.negotiationError;throw e;}});
  }
  async poll(){if(this.polling||!this.profile)return;this.polling=true;try{this.measureMic();const q=await this.api('poll',{after:this.ack,talk:this.talking,target:this.target,level:this.talking?this.level:null});this.members=q.members;this.sessionName=q.sessionName;this.error=[...this.links.values()].find(l=>l.negotiationError)?.negotiationError||'';this.applyListen();this.refreshTalk();
    const ids=new Set(q.members.filter(m=>m.id!==this.profile.id&&m.online).map(m=>m.id));for(const id of this.links.keys())if(id!==this.host&&!ids.has(id))this.remove(id);
    for(const id of ids){const generation=q.members.find(m=>m.id===id)?.generation??1;if(this.links.has(id)&&this.links.get(id).generation!==generation)this.remove(id);if(!this.links.has(id)){this.make(id);if(this.profile.id<id)await this.offerTo(id);}}
    for(const s of q.signals){if(s.generation==null||q.members.some(m=>m.id===s.from&&(m.generation??1)===s.generation))await this.receive(s);this.ack=Math.max(this.ack,s.seq);}
    if(++this.statsPoll%4===0)await this.stats();this.changed();
    if(this.localConnection&&this.directReady()){this.resumeAttempts=0;this.localConnection.state('CONNECTED');}
  }catch(e){this.error=e.message;if(!this.directReady())this.push(false);if(this.localConnection&&!this.directReady())this.resumeLocal().catch(()=>{});this.changed();}finally{this.polling=false;}}
  measureMic(){if(this.analyser&&(!this.meterNode||Date.now()-this.captureAt>1500)){const a=new Float32Array(this.analyser.fftSize);this.analyser.getFloatTimeDomainData(a);this.level=Math.max(-120,20*Math.log10(Math.max(1e-6,Math.sqrt(a.reduce((s,v)=>s+v*v,0)/a.length))));}
    for(const l of this.links.values())if(l.receiveAnalyser){const a=new Float32Array(l.receiveAnalyser.fftSize);l.receiveAnalyser.getFloatTimeDomainData(a);l.receiveLevel=Math.max(-120,20*Math.log10(Math.max(1e-6,Math.sqrt(a.reduce((s,v)=>s+v*v,0)/a.length))));}
  }
  eligible(id){const m=this.members.find(m=>m.id===id);return this.target==='all'||this.target==='user:'+id||this.target==='leader'&&m?.leader||this.target==='group:'+m?.group;}
  listenEligible(id){const m=this.members.find(m=>m.id===id);return this.listenTarget==='all'||this.listenTarget==='user:'+id||this.listenTarget==='leader'&&m?.leader||this.listenTarget==='group:'+m?.group;}
  applyListen(){const allowed=this.members.find(m=>m.id===this.profile?.id)?.canListen!==false;for(const [id,l] of this.links)if(l.audio)l.audio.muted=this.muted||!allowed||this.members.find(m=>m.id===id)?.canTalk===false||this.mutes.has(id)||!this.listenEligible(id);}
  listen(target){this.listenTarget=target;this.applyListen();this.changed();}
  refreshTalk(){if(this.members.find(m=>m.id===this.profile?.id)?.canTalk===false){this.talkControl.stop();this.stopTest();this.talkRequested=false;}this.talking=!!this.talkRequested&&!this.muted&&!!this.microphone&&this.members.find(m=>m.id===this.profile?.id)?.canTalk!==false&&[...this.links].some(([id,l])=>l.pc.connectionState==='connected'&&l.pc.getTransceivers().some(t=>t.sender.track===l.track&&['sendrecv','sendonly'].includes(t.currentDirection))&&this.eligible(id));for(const [id,l] of this.links)if(l.track)l.track.enabled=this.talking&&this.eligible(id);this.changed();}
  push(active){if(!active)this.stopTest();this.talkControl.active(!!active&&!this.muted&&!!this.microphone&&this.members.find(m=>m.id===this.profile?.id)?.canTalk!==false,Date.now());this.talkRequested=this.talkControl.requested;this.refreshTalk();}
  destination(target){this.target=target;this.refreshTalk();}
  panic(active){this.muted=active;if(active){this.talkControl.stop();this.stopTest();this.talkRequested=false;}this.refreshTalk();this.applyListen();this.changed();}
  volume(value){this.master=Number.isFinite(value)?Math.max(0,Math.min(1,value)):0;for(const l of this.links.values())if(l.audio)l.audio.volume=this.master;}
  memberMute(id,active){active?this.mutes.add(id):this.mutes.delete(id);this.applyListen();this.changed();}
  enableAudio(){this.audioUnlocked=true;const jobs=[];if(this.context)jobs.push(this.context.resume());for(const l of this.links.values())if(l.audio){const p=l.audio.play();if(p?.then)jobs.push(p.then(()=>{l.audioPending=false;}).catch(()=>{l.audioPending=true;}));}this.changed();return Promise.allSettled(jobs).then(()=>{this.changed();});}
  async enableMicrophone(){if(!this.microphone){await this.microphoneReady();if(!this.microphone)throw Error(this.micError);for(const [id,l] of this.links){l.track=this.microphone.clone();l.track.enabled=false;l.pc.addTrack(l.track,new MediaStream([l.track]));await this.offerTo(id);}}await this.enableAudio();this.refreshTalk();}
  async repairAudio(manual=true){if(manual){this.repairAttempts.clear();this.resumeAttempts=0;}if(this.talkControl.mode!=='HOLD')this.push(false);const control=this.links.get(this.host)?.channel;if((!control||control.readyState!=='open')&&!this.localConnection)throw Error('DIRECT_LINK_LOST');for(const [id,l] of this.links){const n=this.repairAttempts.get(id)||0;if(n>=3){this.error='Audio repair limit reached. Check local routing and TEST AUDIO, then retry manually.';continue;}if(l.pc.signalingState==='stable'){this.repairAttempts.set(id,n+1);await this.offerTo(id,true);}}this.changed();}
  async stats(){for(const [id,l] of this.links){const report=await l.pc.getStats();const m={};for(const s of report.values()){
    if(s.type==='transport'){m.dtls=s.dtlsState;const pair=report.get(s.selectedCandidatePairId);if(pair){m.selectedCandidatePair=pair.id;for(const [prefix,key] of [['local','localCandidateId'],['peer','remoteCandidateId']]){const c=report.get(pair[key]);if(c){for(const k of ['address','port','protocol','candidateType'])m[prefix+k[0].toUpperCase()+k.slice(1)]=c[k];if(['relay','srflx'].includes(c.candidateType)){this.error='Chemin audio externe refusé';this.push(false);this.remove(id);}}}}}
    if(s.type==='candidate-pair'&&s.state==='succeeded'&&s.currentRoundTripTime!=null)m.rttMs=s.currentRoundTripTime*1000;
    if(s.type==='outbound-rtp'&&s.kind==='audio'){m.codec=report.get(s.codecId)?.mimeType;m.packetsSent=s.packetsSent;m.bytesSent=s.bytesSent;}
    if(s.type==='inbound-rtp'&&s.kind==='audio'){m.receiveCodec=report.get(s.codecId)?.mimeType;for(const k of ['bytesReceived','totalAudioEnergy','totalSamplesReceived','totalSamplesDuration','audioLevel'])if(s[k]!=null)m[k]=s[k];m.packetsReceived=s.packetsReceived;if(s.jitter!=null)m.jitterMs=s.jitter*1000;if(s.packetsReceived+s.packetsLost>0)m.loss=100*Math.max(0,s.packetsLost)/(s.packetsReceived+s.packetsLost);}
  }m.txPacketsDelta=Math.max(0,(m.packetsSent||0)-(l.metrics.packetsSent||0));m.rxPacketsDelta=Math.max(0,(m.packetsReceived||0)-(l.metrics.packetsReceived||0));l.metrics=m;}}
  remove(id){const l=this.links.get(id);if(!l)return;if(this.talkControl.mode!=='HOLD')this.push(false);l.track?.stop();l.receiveSource?.disconnect();l.audio?.remove();l.pc.close();this.links.delete(id);}
  close(){this.push(false);this.talkRequested=false;clearInterval(this.loop);clearInterval(this.audioTick);clearTimeout(this.safety);for(const id of this.links.keys())this.remove(id);this.raw?.getTracks().forEach(t=>t.stop());this.microphone?.stop();this.context?.close().catch(()=>{});this.raw=null;this.context=null;this.microphone=null;this.analyser=null;this.offer=null;this.localConnection=null;for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(Error('Session fermée'));}this.pending.clear();}
}
