/* FOSA-LAN/1: local WebRTC Opus audio and authenticated coordinator RPC. */
export const lanCandidate = c => {const p=c.split(' '),n=p[4]?.split('.').map(Number);return p[7]==='host'&&(p[4]?.endsWith('.local')||n?.length===4&&n.every(x=>Number.isInteger(x)&&x>=0&&x<=255)&&(n[0]===10||n[0]===192&&n[1]===168||n[0]===172&&n[1]>=16&&n[1]<=31));};
export const lanSdp = s => s.split('\r\n').filter(l=>!l.startsWith('a=candidate:')||lanCandidate(l.slice(2))).join('\r\n');
export async function pack(value){const stream=new Blob([JSON.stringify(value)]).stream().pipeThrough(new CompressionStream('deflate'));const a=new Uint8Array(await new Response(stream).arrayBuffer());return btoa(String.fromCharCode(...a)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
export async function unpack(value){if(value.length>18000)throw Error('Invitation trop grande');const a=Uint8Array.from(atob(value.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));const stream=new Blob([a]).stream().pipeThrough(new DecompressionStream('deflate'));const reader=stream.getReader();let count=0;const chunks=[];while(true){const {value,done}=await reader.read();if(done)break;count+=value.length;if(count>32768){await reader.cancel();throw Error('Invitation trop grande');}chunks.push(value);}return JSON.parse(await new Blob(chunks).text());}
const gather = pc => pc.iceGatheringState==='complete'?Promise.resolve():new Promise(resolve=>{const end=()=>{pc.removeEventListener('icegatheringstatechange',check);clearTimeout(timer);resolve();};const check=()=>{if(pc.iceGatheringState==='complete')end();};const timer=setTimeout(end,3500);pc.addEventListener('icegatheringstatechange',check);});
const resumeStore=code=>'fosa-lan-session:'+code;
function resumeIdentity(code){let saved;try{saved=JSON.parse(localStorage.getItem(resumeStore(code))||'null');}catch{}
  const clientKey=/^[a-f0-9]{32}$/.test(saved?.clientKey)?saved.clientKey:crypto.randomUUID().replaceAll('-','');
  const identity={clientKey,profile:saved?.profile};try{localStorage.setItem(resumeStore(code),JSON.stringify(identity));}catch{}return identity;
}
export class WebLanClient {
  constructor(changed=()=>{}){this.changed=changed;this.links=new Map();this.pending=new Map();this.serial=0;this.ack=0;this.members=[];this.target='all';this.talking=false;this.muted=false;this.master=.75;this.mutes=new Set();this.microphone=null;this.level=null;this.profile=null;this.error='';}
  async microphoneReady(){try{const raw=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});this.raw=raw;this.context=new AudioContext({latencyHint:'interactive',sampleRate:48000});await this.context.resume();const source=this.context.createMediaStreamSource(raw),hpf=this.context.createBiquadFilter(),compressor=this.context.createDynamicsCompressor(),dest=this.context.createMediaStreamDestination();hpf.type='highpass';hpf.frequency.value=100;compressor.threshold.value=-12;compressor.knee.value=4;compressor.ratio.value=12;compressor.attack.value=.003;compressor.release.value=.15;this.analyser=this.context.createAnalyser();this.analyser.fftSize=512;source.connect(hpf).connect(compressor).connect(this.analyser).connect(dest);this.microphone=dest.stream.getAudioTracks()[0];this.micError='';}catch(e){this.micError='Microphone bloqué. Écoute seule ; touche ENABLE MICROPHONE et autorise son accès.';}}
  make(id,manual=false){if(this.links.has(id))return this.links.get(id);const pc=new RTCPeerConnection({iceServers:[],bundlePolicy:'max-bundle'});const link={pc,track:null,audio:null,audioPending:false,channel:null,remote:false,ice:[],manual,generation:this.members.find(m=>m.id===id)?.generation??1,metrics:{}};this.links.set(id,link);
    if(this.microphone){link.track=this.microphone.clone();link.track.enabled=false;pc.addTrack(link.track,new MediaStream([link.track]));}else pc.addTransceiver('audio',{direction:'recvonly'});
    pc.onicecandidate=e=>{if(this.links.get(id)===link&&e.candidate&&lanCandidate(e.candidate.candidate)&&!link.manual)this.signal(id,'ice',e.candidate.toJSON()).catch(()=>{});};
    pc.onconnectionstatechange=()=>{if(pc.connectionState==='failed'||pc.connectionState==='disconnected')this.push(false);this.changed();};
    pc.ontrack=e=>{if(this.links.get(id)!==link)return;link.audio?.remove();const audio=document.createElement('audio');audio.autoplay=true;audio.setAttribute('playsinline','');audio.srcObject=e.streams[0]||new MediaStream([e.track]);audio.volume=this.master;audio.muted=this.muted||this.mutes.has(id);document.body.append(audio);link.audio=audio;audio.play().catch(()=>{link.audioPending=true;this.changed();});};
    pc.ondatachannel=e=>this.wire(link,e.channel);return link;
  }
  wire(link,c){link.channel=c;c.onmessage=e=>{try{const q=JSON.parse(e.data);const p=this.pending.get(q.requestId);if(p){clearTimeout(p.timer);this.pending.delete(q.requestId);q.error?p.reject(Error(q.error)):p.resolve(q.data);}}catch{}};c.onopen=()=>this.changed();}
  async prepare({name,role='',code}){name=String(name??'').trim();role=String(role).trim();code=String(code??'').trim();if(!name||name.length>40||role.length>40)throw Error('Nom ou instrument invalide');if(!/^[0-9]{6}$/.test(code))throw Error('Code de session à 6 chiffres requis');this.joinCode=code;this.resume=resumeIdentity(code);await this.microphoneReady();const l=this.make('host',true);this.wire(l,l.pc.createDataChannel('fosa-mobile'));await l.pc.setLocalDescription(await l.pc.createOffer());await gather(l.pc);this.offer=await pack({type:'offer',name,role,code,client:'Web fallback',clientKey:this.resume.clientKey,resumeToken:this.resume.profile?.token||'',sdp:lanSdp(l.pc.localDescription.sdp)});this.changed();return 'fosa://mobile-pair?data='+this.offer;}
  async accept(value){value=value.includes('#answer=')?value.split('#answer=')[1]:value.trim();const q=await unpack(value);if(q.type!=='answer'||!q.profile?.token)throw Error('Réponse QR invalide');const l=this.links.get('host');if(!l)throw Error('L’invitation a expiré. Crée une nouvelle invitation Web.');await l.pc.setRemoteDescription({type:'answer',sdp:lanSdp(q.sdp)});this.profile=q.profile;this.host=q.host;this.links.delete('host');this.links.set(q.host,l);l.remote=true;if(this.joinCode){try{localStorage.setItem(resumeStore(this.joinCode),JSON.stringify({clientKey:this.resume.clientKey,profile:q.profile}));}catch{}}this.loop=setInterval(()=>this.poll(),500);this.changed();}
  forget(){if(this.joinCode)try{localStorage.removeItem(resumeStore(this.joinCode));}catch{}this.resume=null;}
  api(path,body={}){const c=this.links.get(this.host)?.channel;if(!c||c.readyState!=='open')return Promise.reject(Error('Connexion LAN en cours'));const requestId=++this.serial;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(requestId);reject(Error('Hôte local inaccessible'));},4000);this.pending.set(requestId,{resolve,reject,timer});c.send(JSON.stringify({requestId,path,body}));});}
  signal(to,type,data){return this.api('signal',{to,type,data});}
  async offerTo(id){const l=this.make(id);if(!l.channel)this.wire(l,l.pc.createDataChannel('fosa-mobile'));await l.pc.setLocalDescription(await l.pc.createOffer());await this.signal(id,'offer',{type:'offer',sdp:lanSdp(l.pc.localDescription.sdp)});}
  async receive({from,type,data}){if(type==='reset'){this.remove(from);this.make(from);if(this.profile.id<from)await this.offerTo(from);return;}const l=this.make(from);
    if(type==='ice'){if(!lanCandidate(data.candidate))return;if(l.remote)await l.pc.addIceCandidate(data);else l.ice.push(data);return;}
    if(!['offer','answer'].includes(type))return;if(type==='answer'&&l.pc.signalingState==='stable')return;await l.pc.setRemoteDescription({type,sdp:lanSdp(data.sdp)});l.remote=true;for(const c of l.ice)await l.pc.addIceCandidate(c);l.ice=[];
    if(type==='offer'){await l.pc.setLocalDescription(await l.pc.createAnswer());await this.signal(from,'answer',{type:'answer',sdp:lanSdp(l.pc.localDescription.sdp)});}
  }
  async poll(){if(this.polling||!this.profile)return;this.polling=true;try{this.measureMic();const q=await this.api('poll',{after:this.ack,talk:this.talking,target:this.target,level:this.talking?this.level:null});this.members=q.members;this.sessionName=q.sessionName;this.error='';
    const ids=new Set(q.members.filter(m=>m.id!==this.profile.id&&m.online).map(m=>m.id));for(const id of this.links.keys())if(id!==this.host&&!ids.has(id))this.remove(id);
    for(const id of ids){const generation=q.members.find(m=>m.id===id)?.generation??1;if(this.links.has(id)&&this.links.get(id).generation!==generation)this.remove(id);if(!this.links.has(id)){this.make(id);if(this.profile.id<id)await this.offerTo(id);}}
    for(const s of q.signals){if(s.generation==null||q.members.some(m=>m.id===s.from&&(m.generation??1)===s.generation))await this.receive(s);this.ack=Math.max(this.ack,s.seq);}
    if(this.serial%4===0)await this.stats();this.changed();
  }catch(e){this.error=e.message;this.push(false);this.changed();}finally{this.polling=false;}}
  measureMic(){if(!this.analyser)return;const a=new Float32Array(this.analyser.fftSize);this.analyser.getFloatTimeDomainData(a);this.level=Math.max(-120,20*Math.log10(Math.max(1e-6,Math.sqrt(a.reduce((s,v)=>s+v*v,0)/a.length))));}
  eligible(id){const m=this.members.find(m=>m.id===id);return this.target==='all'||this.target==='user:'+id||this.target==='leader'&&m?.leader||this.target==='group:'+m?.group;}
  push(active){this.talking=!!active&&!this.muted&&!!this.microphone&&[...this.links].some(([id,l])=>l.pc.connectionState==='connected'&&this.eligible(id));if(this.talking){clearTimeout(this.safety);this.safety=setTimeout(()=>this.push(false),30000);}for(const [id,l] of this.links)if(l.track)l.track.enabled=this.talking&&this.eligible(id);this.changed();}
  destination(target){this.push(false);this.target=target;this.changed();}
  panic(active){this.muted=active;if(active)this.push(false);for(const l of this.links.values())if(l.audio)l.audio.muted=active||this.mutes.has([...this.links].find(([,v])=>v===l)?.[0]);this.changed();}
  volume(value){this.master=Number.isFinite(value)?Math.max(0,Math.min(1,value)):0;for(const l of this.links.values())if(l.audio)l.audio.volume=this.master;}
  memberMute(id,active){active?this.mutes.add(id):this.mutes.delete(id);const l=this.links.get(id);if(l?.audio)l.audio.muted=active||this.muted;}
  async enableAudio(){await this.context?.resume();for(const l of this.links.values())if(l.audio){await l.audio.play();l.audioPending=false;}this.changed();}
  async enableMicrophone(){if(!this.microphone){await this.microphoneReady();if(!this.microphone)throw Error(this.micError);for(const [id,l] of this.links){l.track=this.microphone.clone();l.track.enabled=false;l.pc.addTrack(l.track,new MediaStream([l.track]));await this.offerTo(id);}}await this.enableAudio();this.changed();}
  async stats(){for(const l of this.links.values()){const report=await l.pc.getStats();const m={};for(const s of report.values()){if(s.type==='candidate-pair'&&s.state==='succeeded'&&s.currentRoundTripTime!=null)m.rttMs=s.currentRoundTripTime*1000;if(s.type==='inbound-rtp'&&s.kind==='audio'){if(s.jitter!=null)m.jitterMs=s.jitter*1000;if(s.packetsReceived+s.packetsLost>0)m.loss=100*Math.max(0,s.packetsLost)/(s.packetsReceived+s.packetsLost);}}l.metrics=m;}}
  remove(id){const l=this.links.get(id);if(!l)return;l.track?.stop();l.audio?.remove();l.pc.close();this.links.delete(id);}
  close(){this.push(false);clearInterval(this.loop);clearTimeout(this.safety);for(const id of this.links.keys())this.remove(id);this.raw?.getTracks().forEach(t=>t.stop());this.microphone?.stop();this.context?.close().catch(()=>{});this.raw=null;this.context=null;this.microphone=null;this.analyser=null;this.offer=null;for(const p of this.pending.values()){clearTimeout(p.timer);p.reject(Error('Session fermée'));}this.pending.clear();}
}
